### PR TITLE
Add ForceFree executable

### PR DESCRIPTION
**Pull request by yoonso0-0**
## Proposed changes

Add a plain DG executable (without IMEX, without subcell) for ForceFree evolution system.

Dependent on 
- [x] #4890 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by yoonso0-0** [comment]
Rebased

**Comment by yoonso0-0** [comment]
Rebased on develop

**Comment by yoonso0-0** [comment]
Rebased on develop

**Comment by yoonso0-0** [comment]
Okay, I think this is ready for the review

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
