### PR TITLE
Add libsharp to docker

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes
Modified the Docker.buildenv to include spack calls for bringing in libsharp.
Assumes a version of spack which has brought in the libsharp package pull
request.

### Types of changes:

- [ ] New feature

### Component:

- [ ] Build system

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by nilsdeppe — COMMENTED** [review]
I don't think this will actually work as is. Are you okay with me testing this and setting it up instead?

**Comment by moxcodes** [comment]
Ah, because the build script checks out a specific spack version. Sure, feel free to do what you need to do. I'd mostly anticipated that we'd wait until my spack PR got in before merging this, but if we'd like it earlier we can probably automatically pull and merge the `package/libsharp` branch from my spack fork into the stable version branch previously chosen.

**Comment by nilsdeppe** [comment]
Could you link us to the spack PR?

**Comment by moxcodes** [comment]
~~[spack PR 1066](https://github.com/sxs-collaboration/spectre/pull/1066)~~
oops
[spack PR 9530](https://github.com/spack/spack/pull/9530)

**Comment by nilsdeppe** [comment]
This links to a spectre PR

**Comment by moxcodes** [comment]
fixed

**Comment by moxcodes** [comment]
in case you didn't have time yet to get it up and working, I've updated this PR with the build script I used successfully to make the image I'll be using locally to start working on the spectre spin-weight interface (not that you necessarily want to keep the bit where it takes the spack from my fork).

**Comment by moxcodes** [comment]
Done in [PR1152](https://github.com/sxs-collaboration/spectre/pull/1152)

**Pull request closed without merging**
