### PR TITLE
Enable Pybindings by default

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

I tested building and running the Pybindings on Wheeler and Caltech HPC. @geoffrey4444 could you make sure they run on Ocean? You don't even have to be on this branch, just set `-D BUILD_PYTHON_BINDINGS=ON` in your CMake config, build the `all-pybindings` target and run `ctest -R Python`.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
I built and tested pybindings on Ocean. Thanks for building charm with the patch @geoffrey4444! Deleted the outdated `ocean_gcc` environment.

**Review by nilsdeppe — APPROVED** [review]

**Review by knelli2 — APPROVED** [review]
Tried this on wheeler and works well.

**Comment by nilsdeppe** [comment]
Fails on Ocean:
```
Test project /home/nils/spectre/build
    Start 1468: Unit.Visualization.Python.PlotDatFile
1/1 Test #1468: Unit.Visualization.Python.PlotDatFile ...***Failed    6.42 sec
Traceback (most recent call last):
  File "/home/nils/spectre/tests/Unit/Visualization/Python/Test_PlotDatFile.py", line 4, in <module>
    import spectre.Visualization.PlotDatFile as plot_dat
  File "/home/nils/spectre/build/bin/python/spectre/Visualization/PlotDatFile.py", line 16, in <module>
    import matplotlib.pyplot as plt
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/colorbar.py", line 38, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.font_manager as font_manager
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1447, in <module>
    fontManager = _load_fontmanager()
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1442, in _load_fontmanager
    json_dump(fm, fm_path)
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/font_manager.py", line 990, in json_dump
    with cbook._lock_path(filename), open(filename, 'w') as fh:
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/opt/ohpc/pub/apps/python/3.9.5/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1854, in _lock_path
    raise TimeoutError("""\
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /home/nils/.cache/matplotlib/fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
```

**Comment by nilsdeppe** [comment]
I have no idea if this was an issue previously...

**Comment by knelli2** [comment]
@nilsdeppe I just tested on ocean but didn't get that error

**Comment by nilsvu** [comment]
Also tried again and tests passed. Thanks for testing too @knelli2! @nilsdeppe maybe just `rm /home/nils/.cache/matplotlib/fontlist-v330.json.matplotlib-lock`? Could be a leftover from some failed script.

**Review by nilsdeppe — APPROVED** [review]
Deleting the file fixed it. Thanks!

**Comment by nilsdeppe** [comment]
CI failure is unrelated timeout

**Pull request merged**
