### PR TITLE
Update Minerva environment

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Adds libsharp and python modules

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]
I can't test, but I assume it works. could @hrueter test this?

**Review by kidder — DISMISSED** [review]

**Comment by nilsvu** [comment]
Good idea, @hrueter could you be the human Travis for this? :)

**Comment by hrueter** [comment]
The human Travis says:

> Can not execute support/Environments/minerva_gcc.sh: No permission 

The file is missing the executable flag.

> I can not find the modules.

You have to load the SPACK environment before loading the modules.

> Scanning dependencies of target module_Main
> [  0%] Generating Main.decl.h, Main.def.h
> [  0%] Built target module_Main
> [  0%] Building CXX object CMakeFiles/PCH_SPECTRE_DEPENDENCIES.dir/tmp/.SpectrePchForDependencies.cpp.o
> g++: Fehler: unbekannte Kommandozeilenoption »-Wdocumentation«
> g++: Fehler: unbekannte Kommandozeilenoption »-Wnewline-eof«

This is broken due to this commit: https://github.com/sxs-collaboration/spectre/commit/ce1ac511438480d2827e86159b0b8fb1ddc80cdb#diff-5a96f5da6af64f7edc54537b85b3390f
The new `check_and_add_cxx_flag` seems to be broken on Minerva not filtering out the clang options.

**Comment by wthrowe** [comment]
> > Scanning dependencies of target module_Main
> > [  0%] Generating Main.decl.h, Main.def.h
> > [  0%] Built target module_Main
> > [  0%] Building CXX object CMakeFiles/PCH_SPECTRE_DEPENDENCIES.dir/tmp/.SpectrePchForDependencies.cpp.o
> > g++: Fehler: unbekannte Kommandozeilenoption »-Wdocumentation«
> > g++: Fehler: unbekannte Kommandozeilenoption »-Wnewline-eof«
> 
> This is broken due to this commit: [ce1ac51#diff-5a96f5da6af64f7edc54537b85b3390f](https://github.com/sxs-collaboration/spectre/commit/ce1ac511438480d2827e86159b0b8fb1ddc80cdb#diff-5a96f5da6af64f7edc54537b85b3390f)
> The new `check_and_add_cxx_flag` seems to be broken on Minerva not filtering out the clang options.

That's a locale issue.  Probably forcing `LC_ALL=POSIX` for the test compile (line 41ish of the changed file) will fix it.  That would also let us remove some of the quote handling logic from later in the function.

**Comment by nilsvu** [comment]
thanks @wthrowe, that should do it.

@hrueter:

```sh
$ human-travis rebuild 1228
```

**Comment by wthrowe** [comment]
You can remove all the code for handling unicode quotes (the "GCC_STYLE_QUOTE" stuff) from that file as well, since that won't happen in the POSIX locale.

**Comment by wthrowe** [comment]
Looks good.  Squash.

**Comment by hrueter** [comment]
Human Travis says:

> [ 56%] Building CXX object tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/Test_ImposeBoundaryConditions.cpp.o
g++: interner Compiler-Fehler: Speicherzugriffsfehler (Programm cc1plus)
Bitte senden Sie einen vollständigen Fehlerbericht auf Englisch ein;
inclusive vorverarbeitetem Quellcode, wenn es dienlich ist.
Weitere Hinweise finden Sie unter »<https://gcc.gnu.org/bugs/>«.
make[3]: *** [tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/Test_ImposeBoundaryConditions.cpp.o] Fehler 4
make[2]: *** [tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/all] Fehler 2
make[1]: *** [CMakeFiles/test-executables.dir/rule] Fehler 2
make: *** [test-executables] Fehler 2

I am not able to compile on Minerva due to some internal compiler error. °~°

**Comment by wthrowe** [comment]
I can reproduce the error locally with 6.4.0 and 7.3.0 (but 8.2.0 succeeds).  I can also reproduce it on develop, but Travis is fine with that so I'm not sure what's going on.

Edit: Debug vs. release did not matter.

**Comment by wthrowe** [comment]
I believe I have a patch for the ICE.  Once I've verified that it works in all my configurations I'll submit a PR.

**Comment by kidder** [comment]
@nilsleiffischer #1243 has been merged, so this can be rebased...

**Comment by nilsvu** [comment]
done @kidder

**Comment by nilsvu** [comment]
@hrueter could you try again please?

**Comment by hrueter** [comment]
Results from the human Travis:
- `make` compiles with no problems
- `make test-executables` has no problems
- 1 out of 931 tests fails

> Start 918: COMPILATION_TEST_TEST_DIFFERENT_COMPILERS
918/931 Test #918: COMPILATION_TEST_TEST_DIFFERENT_COMPILERS ..................................***Failed  Required regular expression not found.Regex=[static assertion failed: assert with GCC 6 or newer]  6.38 sec

The problem is that due to the german local static_assert actually returns:
> 918: /home/rueter/spectre/tests/Unit/TestCompilationFramework.cpp:24:1: Fehler: statische Erklärung gescheitert: assert with GCC 6 or newer
918:  static_assert(false, "assert with GCC 6 or newer");
918:  ^~~~~~~~~~~~~

possible fix, that I tested to be working:
in tests/Unit/TestCompilationFramework.cpp remove `static assertion failed: ` from the regular expression

**Review by hrueter — APPROVED** [review]

**Comment by nilsvu** [comment]
Thanks @hrueter, I wish the robot-Travis would do this kind of debugging, too 😄 Apparently humans are still better than robots 💁‍♂️

@sxs-collaboration/spectre-core-devs I suppose generalizing that test to different locales is out of scope for this PR, so this PR would be done from my perspective.

**Review by nilsdeppe — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]
I agree that there is no need to fix the test in this PR.

**Comment by kidder** [comment]
Created #1250 to deal with the unrelated test failure

**Pull request merged**
