### PR TITLE
Use Python 3.7 module on Wheeler

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Seems to work fine:

```
$ spectre_run_cmake
$ make -j6 all-pybindings
$ ctest -R .Python
100% tests passed, 0 tests failed out of 23
```

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I have a vague recollection of things like HDF5 not working correctly... What you tested is insufficient. You need to at least make sure you can run an evolution and run `GenerateXdmf` on it. Probably should also run _all_ the test, not just the python ones. Python mucks with all the C, C++, and fortran libraries.

**Review by nilsdeppe — CHANGES_REQUESTED** [review]
See previous comment...

**Comment by nilsvu** [comment]
Seems to work fine. I built `test-executables` and ran `ctest`:

```
100% tests passed, 0 tests failed out of 1555
```

This includes Python tests, and tests of `GenerateXdmf`, `Render1D`, etc. I also ran a scalar wave and an elliptic solve and `GenerateXdmf` over their output.

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
Thanks for checking all that :)

**Pull request merged**
