### PR TITLE
Send error messages to stderr

### LINKED ISSUE #1164: I/O buffering changes in glibc 2.27 can break tests
Starting recently, I found that some failure tests are failing under some setups.  The failure I see are Integration.Parallel.AlgorithmBadBoxApply, Integration.Parallel.AlgorithmNestedApply1, and Integration.Parallel.AlgorithmNestedApply2 in various optimized gcc builds.  (Failures occur in some builds and not others, but are reproducible when they occur.)  The underlying problem affects all of my compiler configurations, however, and I think which tests fail is just chance.

The problem is that the error messages are not being flushed when the test processes terminate, so the output is truncated.  If it is sufficiently truncated then the error message searched for in an ERROR or ASSERT test is missing and the test fails.  As a simple verification of this `bin/Test_AlgorithmNestedApply2 2>/dev/null` produces the expected output, but `bin/Test_AlgorithmNestedApply2 2>/dev/null | cat` is truncated.  For example, in one of my setups where the test passes the "cat" version output ends with
```
  [0:9] _ZN8Parallel16Algorithm_detail21simple_action_visitorI36error_call_single_action_from_actionN2db7DataBoxIN7brigand4listIJEEEEEJS8_EJRN6tuples11TaggedTupleIJEEERNS_16ConstGlobalCacheI17TestMetavariablesEERKN5cpp179void_typeES7_P9ComponentISE_EEEEvRN5boost7variantIDpT1_EEDpOT2_+0xd9  [0x44fdb9]
  [0:10] _ZN8Parallel13AlgorithmImplI9ComponentI17TestMetavariablesEN7brigand4listI
```
(with no newline).  There should be 34 lines in the backtrace.  In the failing configurations there is no output at all.

I recently updated from glibc 2.26 to 2.27. Looking at the change log for glibc 2.27, I find
```
* The abort function terminates the process immediately, without flushing
  stdio streams.  Previous glibc versions used to flush streams, resulting
  in deadlocks and further data corruption.  This change also affects
  process aborts as the result of assertion failures.
```
That looks likely to be the cause of the issue.

I'm not sure what we can do about this.  The correct thing would be to flush output before calling abort(), but I believe both the output and abort() call are done by charm.  Unbuffering stdout would also do it, but as far as I can tell the buffering state can only be changed before anything is written which, again, is inside charm.

Edit: A third solution: send the error messages to stderr where they should be anyway.  But again, that's charm.

### PR DESCRIPTION
**Pull request by wthrowe**
Fixes #1164

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
I don't understand the Travis failures.  They appear to be python-related.  Can someone else take a look at them?

**Comment by nilsdeppe** [comment]
I think you'll need to add a mock-ish `CmiError` function to `src/PythonBindings/CharmCompatibility.cpp`. Because getting Charm++ libs to link with anything was rather painful, it was easier to swap in non-parallel variants of some of the core functions. Does that make sense?

**Comment by wthrowe** [comment]
Thanks, I get it now.  Let's see if this version works.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
The GCC builds have a warning on them

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
