### PR TITLE
Update fluxes on external boundaries

### LINKED ISSUE #1142: Fluxes are not updated on external boundaries
# Bug reports:

Neither `dg::ComputeNonvonservativeBoundaryFluxes` nor `dg::ImposeDirichletBoundaryConditions` update the `Interface<BoundaryDirectionsInterior, NormalDotFlux<variables_tag>>`. This is a potential source of error. For instance, I don't see where in `EvolveScalarWave` these are updated.

### Expected behavior:

`Interface<BoundaryDirectionsInterior, NormalDotFlux<variables_tag>>` is computed in each step of the algorithm

### Current behavior:

It remains as set in `InitializeElement`.

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Fixes #1142. Needed also for elliptic systems.

### Types of changes:

- [x] Bugfix

### Component:

- [x] Code

### Code review checklist

- [x] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
Since I'd like to use this action also for elliptic systems to update the N.F on internal and external element boundaries, should we rename it? Suggestions:
- `ComputeFluxes` (could be ambiguous with numerical flux, which is computed in `ApplyFluxes`?)
- `ComputeBoundaryFluxes` (doesn't cure the ambiguity)
- `ComputeNormalDotFluxes` (also doesn't cure the ambiguity, and the "NormalDot" is an implementation detail)

**Edit:** We decided to defer renaming this until we know more about where this action is applicable

**Review by wthrowe — DISMISSED** [review]

**Comment by kidder** [comment]
@nilsleiffischer this is not compiling with gcc6

**Comment by nilsvu** [comment]
@kidder yes and I don't understand why..

**Comment by wthrowe** [comment]
Calling the function as `ComputeNonconservativeBoundaryFluxes::apply_flux<Metavariables>` works.  Presumably a gcc-6 bug.

Unrelatedly, `volume_dim` in the test is now unused.

**Comment by nilsvu** [comment]
Thanks @wthrowe!

This should be ready now @kidder @nilsdeppe

**Review by nilsdeppe — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
