### PR TITLE
Delete unused fluxcomm functions

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

These functions were left-over from #1725.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by wthrowe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
This needs to be rebased

**Comment by kidder** [comment]
@nilsleiffischer this needs a rebase

**Comment by fmahebert** [comment]
When rebasing, please delete `FluxCommunicationTypes.hpp` from the CMakeLists.txt

**Comment by kidder** [comment]
@nilsleiffischer this has a conflict

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
