### PR TITLE
Update Valencia

### PR DESCRIPTION
**Pull request by carmaza**
## Proposed changes

This PR adds the updates needed in Valencia in order to evolve it. (Executable in a more recent PR).

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
Could you please split this into several smaller PRs? That would make it easier to review, especially if the changes don't all depend on each other.

**Comment by carmaza** [comment]
Sure. I'll put the independent commits in different PRs.

**Comment by nilsdeppe** [comment]
Okay, thank you so much! Feel free to request me as a reviewer on them :)

**Comment by nilsdeppe** [comment]
Re our in person discussion about waiting from frame renames: I don't think it's worth it or necessary. There will be type aliases that will allow us to easily transition from the old names to the new, so please don't feel like anything should wait on that.

**Comment by carmaza** [comment]
This PR was replaced by #1797 #1798 #1799 and #1800 (all independent from each other) so feel free to close this one.

**Comment by nilsdeppe** [comment]
This has been replaced by other PRs so closing.

**Pull request closed without merging**
