### PR TITLE
Encourage formaline CI test to reuse compiler cache

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Make sure to use the same compiler flags as the full build.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]
I'm fine with the changes, though as far as I can tell it's not working :(

**Comment by nilsvu** [comment]
Indeed it is not. Don't know why and probably not worth spending a lot more time on.. :(

**Comment by nilsdeppe** [comment]
Yea, it seems weird to me too. I don't know how ccache memorizes things. Maybe it's using full paths and so the paths mismatch? :shrug:

**Comment by nilsvu** [comment]
Did some debugging it it was indeed a relative paths issue. Pushed another commit that worked with a test run on my fork (https://github.com/nilsvu/spectre/actions/runs/6030237314/job/16361609923).

**Review by nilsdeppe — APPROVED** [review]
Nice :D

**Comment by nilsvu** [comment]
When merging this best also merge https://github.com/sxs-collaboration/spectre/pull/5408 at the same time so CI caches only get invalidated once.

**Comment by nilsvu** [comment]
Seems to work now for most builds. (the clang-11 ASAN build is expected to miss caches; not sure about the clang-13 build)

**Pull request merged**
