### PR TITLE
Add Visualization directory

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

This PR adds a top-level `Visualization` directory and moves the `GenerateXdmf` script there. It builds a `spectre.Visualization` Python module, so that e.g. the `GenerateXdmf` script is accessible via `python -m spectre.Visualization.GenerateXdmf`. This PR also adds a test.

I expect that, in addition to post-processing visualization scripts, we will also add in-situ visualization functionality to our code in the future, which this directory is also for.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I'd rather have this be a top level directory and not be part of the `src`. The reason is that many of the visualization codes will depend on TPLs that won't be available everywhere and are a total nightmare to install.

**Comment by nilsvu** [comment]
@nilsdeppe updated this PR based on what we talked about earlier today

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsvu** [comment]
@kidder @nilsdeppe The `GenerateXdmf` script needs `h5py`, so I added it to the docker container. To use the script we had to install h5py in the container manually before, so pre-installing  is reasonable I think.

**Comment by nilsdeppe** [comment]
I'm building and pushing the updated container now. I will restart travis once that's done.

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
