### PR TITLE
Fix InfoAtLink with Ninja

### PR DESCRIPTION
**Pull request by nilsvu**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Review by moxcodes — DISMISSED** [review]
I have not investigated the generated compiler flags in detail, but this does appear to fix the `ninja` build in the container.

**Review by fmahebert — DISMISSED** [review]
Another empirical "it fixed my builds" approval from me.

Thanks for the quick patch!

**Review by nilsdeppe — DISMISSED** [review]

**Comment by kidder** [comment]
Does not work on my MacBook
```
Fatal Error by charmc in directory /Users/kidder/Codes/SpECTRE/nils_f/spectre/build/src/Evolution/Executables/ScalarWave
   file with unrecognized extension /Users/kidder/ExternalPackages/charm/v6.10.2/multicore-darwin-x86_64/include
charmc exiting...
```

**Comment by nilsvu** [comment]
argh, it's `charmc` choking on perfectly valid compiler invocations. Passing everything through `charmc` is so annoying... let me see if there's a quick workaround

**Comment by kidder** [comment]
develop doesn't compile either for me on my macbook, so if this fixes other builds it should be merged.  @wthrowe does this PR affect your setup?

**Comment by nilsvu** [comment]
@kidder I pushed another commit, please check if that fixes it.

**Comment by wthrowe** [comment]
Neither develop (0d615ebbffeb5937a891b0731d5164a8d04e3f92) nor 0dfabbe35834af25a2902b0971ef8eb7cd45a5a4 build for me.

Edit: Be specific about "develop".

**Comment by nilsvu** [comment]
Could you post the details please @wthrowe?

**Comment by wthrowe** [comment]
What details do you want?

**Comment by nilsvu** [comment]
The error message to start with

**Comment by wthrowe** [comment]
develop:
```
x86_64-pc-linux-gnu-g++: error: unrecognized command-line option ‘-ferror-limit=1’
Fatal Error by charmc in directory /home/wthrowe/spectre-work/src/Executables/Examples/HelloWorldNoCharm
   Command x86_64-pc-linux-gnu-g++ -DCMK_GFORTRAN -D_REENTRANT -I/usr/include/charm -D__CHARMC__=1 -DGIT_DESCRIPTION=v2021.05.03-37-g0d615ebbf -DGIT_BRANCH=develop -DBOOST_MULTI_ARRAY_TYPES_HPP -DBOOST_SP_DISABLE_THREADS -DSPECTRE_SHARED_MEMORY_PARALLELISM_BUILD -I/home/wthrowe/spectre/external -I/home/wthrowe/spectre/src -I/home/wthrowe/spectre/tests/Unit -DSPECTRE_DEBUG -pthread -fuse-ld=gold -march=native -no-pie -isystem /usr/include/charm -isystem /usr/include/catch2 -isystem /home/wthrowe/spectre-work -isystem /home/wthrowe/spectre-work/src -isystem /home/wthrowe/spectre-work/src/Parallel -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -march=native -g -std=c++17 -march=native -O2 -pipe -ggdb -fno-stack-protector -fno-lifetime-dse -fPIC -c /home/wthrowe/spectre-work/tmp/HelloWorldNoCharm_InfoAtLink.cpp -o HelloWorldNoCharm_InfoAtLink.o returned error code 1
charmc exiting...
```
PR:
```
x86_64-pc-linux-gnu-g++: error: unrecognized command-line option ‘-ferror-limit=1’
Fatal Error by charmc in directory /home/wthrowe/spectre-work/src/Executables/Examples/HelloWorldNoCharm
   Command x86_64-pc-linux-gnu-g++ -DCMK_GFORTRAN -D_REENTRANT -I/usr/include/charm -D__CHARMC__=1 -DGIT_DESCRIPTION=v2021.05.03-39-g0dfabbe35 -DGIT_BRANCH=HEAD -DBOOST_MULTI_ARRAY_TYPES_HPP -DBOOST_SP_DISABLE_THREADS -DSPECTRE_SHARED_MEMORY_PARALLELISM_BUILD -I/home/wthrowe/spectre/external -I/home/wthrowe/spectre/src -I/home/wthrowe/spectre/tests/Unit -I/usr/include/charm -I/usr/include/catch2 -I/home/wthrowe/spectre-work -I/home/wthrowe/spectre-work/src -I/home/wthrowe/spectre-work/src/Parallel -DSPECTRE_DEBUG -pthread -fuse-ld=gold -march=native -no-pie -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -march=native -g -std=c++17 -march=native -O2 -pipe -ggdb -fno-stack-protector -fno-lifetime-dse -fPIC -c /home/wthrowe/spectre-work/tmp/HelloWorldNoCharm_InfoAtLink.cpp -o HelloWorldNoCharm_InfoAtLink.o returned error code 1
charmc exiting...
```
(OK that would have been the obvious information if I'd read it more closely.)

**Comment by nilsvu** [comment]
Could you post the content of `BUILD_DIR/Informer/InfoAtLink_flags.txt` as well please?

**Comment by wthrowe** [comment]
```
-DBOOST_MULTI_ARRAY_TYPES_HPP -DBOOST_SP_DISABLE_THREADS -DSPECTRE_SHARED_MEMORY_PARALLELISM_BUILD -I/home/wthrowe/spectre/external -I/home/wthrowe/spectre/src -I/home/wthrowe/spectre/tests/Unit -I/usr/include/charm -I/usr/include/catch2 -I/home/wthrowe/spectre-work -I/home/wthrowe/spectre-work/src -I/home/wthrowe/spectre-work/src/Parallel -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -march=native -g -DSPECTRE_DEBUG -std=c++17
```

**Comment by nilsvu** [comment]
Would you mind trying to just delete the offending `-ferror-limit=1` flag from the `InfoAtLink_flags.txt` file and recompiling?

**Comment by wthrowe** [comment]
That seems to work.  (I only tried HelloWorldNoCharm.)

(I'm going to have to run in about 10 minutes.)

**Comment by nilsvu** [comment]
My suggestion to deal with this issue is: We work around `charmc`'s inability to handle valid compiler invocations by stripping these offending flags, and resolve it properly with #2680. I pushed another commit, please try again.

**Comment by kidder** [comment]
okay the latest fix works for me

**Comment by kidder** [comment]
@moxcodes @fmahebert @nilsdeppe can you confirm this still works for you

**Comment by nilsvu** [comment]
Ok good. I'm signing off for tonight, so if more issues come up that can't wait until tomorrow, just revert #3103.

**Comment by moxcodes** [comment]
My builds in the container still work with ninja on the current hash `3e532d111`

**Comment by nilsdeppe** [comment]
Doesn't work for me:
```
FAILED: bin/Test_AlgorithmNodelock 
: && /home/nils/Downloads/spectre/build/tmp/WrapExecutableLinker.sh /home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/bin/charmc -pthread -module EveryLB  -no-charmrun   -L/home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/lib -fuse-ld=gold  tests/Unit/Parallel/CMakeFiles/Test_AlgorithmNodelock.dir/Test_AlgorithmNodelock.cpp.o -o bin/Test_AlgorithmNodelock  -Wl,-rpath,/usr/local/lib  /usr/lib/x86_64-linux-gnu/libjemalloc.so  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0  lib/libErrorHandling.a  lib/libInformer.a  lib/libOptions.a  lib/libParallel.a  lib/libSystemUtilities.a  lib/libUtilities.a  lib/libEventsAndTriggers.a  lib/libParallel.a  lib/libEventsAndTriggers.a  lib/libInformer.a  lib/libDataStructures.a  lib/libOptions.a  /usr/local/lib/libyaml-cpp.so  lib/libUtilities.a  lib/libErrorHandling.a  lib/libSystemUtilities.a  /usr/lib/x86_64-linux-gnu/libjemalloc.so  tmp/libSpectrePchLib.a  /usr/local/lib/libxsmm.a  /usr/lib/x86_64-linux-gnu/libopenblas.so  -lpthread  -lm  -ldl && :
Fatal Error by charmc in directory /home/nils/Downloads/spectre/build
   file with unrecognized extension .
charmc exiting...
```

Can we revert the other PR and just skip this step completely and go straight to linking Charm++ manually? we've been eliding charm++ in the compilation for this reason forever now

**Comment by nilsvu** [comment]
Yes let's do that #3187. @nilsdeppe could you post your content of `BUILD_DIR/Informer/InfoAtLink_flags.txt` nevertheless?

**Comment by fmahebert** [comment]
I'm happy to revert. Just for the data point, I can confirm commit `3e532d111d` worked for my setup.

**Comment by nilsdeppe** [comment]
I already wiped the source tree and build directory (I used a separate clone to avoid possibly breaking my main repo), sorry

**Pull request closed without merging**
