### PR TITLE
Improve some CLI errors and docs

### LINKED ISSUE #6085: spectre plot slice usability improvements
@ctrandrsn and I ran into some confusion when trying to use this feature. Specifically,

- [x] `spectre plot slice ` happily runs with zero h5 files. It should give an error if you give no files.
- [x] If you don't specify a variable to plot it just lists all of them without actually telling you why it's listing them. Having an error would be helpful.
- [ ] `--slice-extent` is `X Y` while everything else is `X,Y`. Having this be consistent would be nice.
- [x] `--subfile-name` seems to have a default subfile but this isn't document. The HDF5 file we ran on only has 1 subfile so I'm not sure if that's why it could do it. In any case, this should be documented in the help text.
- [x] It seems like `--slice-origin` and the other `--slice` options are all required because if we didn't specify them all we get an error that they must be specified. Could these be marked as required in the help text?
- [x] `--var` also isn't marked as required but is.

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Fixes #6085.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]
This is awesome! Thank you for doing this so quickly! 🚀

**Comment by nilsvu** [comment]
I extended the last commit a bit further with more error message that benefit from the new `RequiredChoicesError`.

**Comment by nilsdeppe** [comment]
Uh oh, looks like CI is now hitting a check you added :)

**Comment by nilsvu** [comment]
Fixed

**Review by knelli2 — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
