### PR TITLE
Move EventAndTriggers OptionTag into its own file

### PR DESCRIPTION
**Pull request by kidder**
This breaks a non-enforced dependency of libGaugeSourceFunctions upon
module_ConstGlobalCache, which can cause the build to fail.

Potential breaking change:  Executables that use EventsAndTriggers will need to 
`#include "Evolution/EventsAndTriggers/Tags.hpp`

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
Should we move the base tag here too?  (I don't remember why I put any of these tags where they are.)

**Comment by nilsdeppe** [comment]
Yea, keeping the base tag in the same place seems like a reasonable thing to do. It'll make them easier to find in the code base. If there's a reason to move them @kidder will either discover it or someone else in the future will :)

**Comment by kidder** [comment]
@wthrowe I've moved the base tag as well

**Review by geoffrey4444 — DISMISSED** [review]

**Comment by wthrowe** [comment]
Looks good.  Squash.

**Comment by kidder** [comment]
@wthrowe I've squashed

**Review by nilsdeppe — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
