### PR TITLE
Add Pybindings for the Poisson DG operator matrix

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

This PR adds test helpers that apply the DG operator without using our parallel infrastructure and exposes the first-order Poisson DG operator to Python. This is now possible because #2037 decoupled the necessary functions.
With the bindings we can retrieve the DG operator matrix on any domain in Python. This is useful for looking at properties of the operator, comparing it to independent implementations and
testing solvers in Python.

Depends on:
- [x] The "Add expand_tuple utility" commit is from #2083 and can be ignored
- [x] The "Make BLAS an imported target" commit is from #2086 
- [x] #2102 

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
`Make BLAS an imported target` does not belong in this PR.

**Comment by nilsvu** [comment]
@nilsdeppe factored out to #2086

**Comment by nilsdeppe** [comment]
This doesn't build...

**Comment by nilsdeppe** [comment]
I feel like you're more likely to get reviewers on this if you split it up... My personal maximum where I'm likely to still review something is about 500 lines, but 200-300 is much better.

**Comment by nilsvu** [comment]
@nilsdeppe yep, started that earlier today with #2187 :)

**Comment by nilsdeppe** [comment]
Sounds good :) :+1:

**Comment by nilsdeppe** [comment]
Can we close this?

**Comment by nilsdeppe** [comment]
Or what is the status of this?

**Comment by nilsvu** [comment]
This is code that is in principle ready for review from my perspective, but it should be split in smaller PRs. I'll close for now and reopen once it's a smaller diff.

**Pull request closed without merging**
