### PR TITLE
Increase timeout of a test

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

This test timed out on CI [here](https://github.com/sxs-collaboration/spectre/runs/5792754883?check_suite_focus=true)

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by knelli2 — APPROVED** [review]
Yeah unfortunately this test is pretty bulky now with the quaternion ODE integration for the rotation map. If we wanted to keep the test times down, I'd suggest splitting up each `test_bbh_time_dependent_factory(-, -)` test into its own `SPECTRE_TEST_CASE`.

**Comment by nilsvu** [comment]
Yea could you take a look at trimming down the test if possible (no particularly high priority, more something to switch to when you're tired of debugging communication deadlocks 😅)? I think splitting into several test cases only hides the issue and adds some test startup overhead. In the another PR you said the ODE integration is performed an excessive number of times, so perhaps we can trim that down significantly?

**Review by nilsdeppe — APPROVED** [review]
I agree with @nilsvu that splitting into multiple tests doesn't actually solve the problem. If it can't be trimmed then that's okay-ish. 30 seconds is long but okay for a few tests that just have a lot of math. We just don't want people to get into the habit of "Oh, I wrote a long test, let me just increase the timeout." But at the same time splitting into multiple tests to get around the timeout is also not really a solution :)

**Comment by knelli2** [comment]
Ok yeah splitting it up isn't the best option. I can take a look and see if I can trim it down, but the test is already pretty exhaustive of the BCO domain. There's just a lot to test with boundary conditions, time dependent maps, different input options, etc.... And as we add more maps/features to the domain, the test is only going to grow. So eventually this will become an issue again, but for now I think this is an ok temporary fix.

**Pull request merged**
