### PR TITLE
Have CMake generate the dependencies of the PCH

### LINKED ISSUE #506: Precompiled header fails to recompile when necessary
After modifying Abort.hpp running make gives
```
[  1%] Built target pch
[  6%] Built target SPHEREPACK
[  6%] Building CXX object src/ApparentHorizons/CMakeFiles/ApparentHorizons.dir/SpherepackIterator.cpp.o
fatal error: file '/home/wthrowe/spectre/src/Parallel/Abort.hpp' has been
      modified since the precompiled header
      '/home/wthrowe/spectre-work/SpectrePch.hpp.gch' was built
note: please rebuild precompiled header
      '/home/wthrowe/spectre-work/SpectrePch.hpp.gch'
1 error generated.
```

### PR DESCRIPTION
**Pull request by wthrowe**
Fixes #506

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### CODE REVIEW

**Review by nilsdeppe — CHANGES_REQUESTED** [review]
This is not portable: "Note that the IMPLICIT_DEPENDS option is currently supported only for Makefile generators and will be ignored by other generators."

https://cmake.org/cmake/help/v3.11/command/add_custom_command.html

**Comment by wthrowe** [comment]
There's a DEPFILE option that apparently does something similar for Ninja.  (They apparently decided not to support IMPLICIT_DEPENDS because of it.)  Unfortunately the documentation is somewhat lacking and we don't test Ninja (and I don't use it), so I wouldn't expect any code I wrote to actually work.

Since I believe you are the only one who uses Ninja, could you write the Ninja-specific code?

**Comment by nilsdeppe** [comment]
Ah neat! I'll play around with this, it looks like it should be reasonably straight forward to get it to work

**Comment by nilsdeppe** [comment]
I'd be happy with an if/else where ninja uses what we currently have for now until I can really figure this out. That way at least make generators are improved

**Comment by nilsdeppe** [comment]
Okay, so I couldn't get the DEPFILE stuff to work (no idea why). I've put something together that creates a dummy lib that is used to track dependencies of the PCH, which should be generator-agnostic. Here is the branch: https://github.com/nilsdeppe/spectre/commits/pch_deps (see the last commit). Let me know what you think of this, and feel free to stick that into this PR if you are happy with it (or modifications to it)

**Comment by wthrowe** [comment]
Closing in favor of #622.

**Pull request closed without merging**
