### PR TITLE
Make std::variant option-parsable

### PR DESCRIPTION
**Pull request by wthrowe**
The alternatives are tried in order.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
Clang <7 bug: https://bugs.llvm.org/show_bug.cgi?id=33222

Marking in progress while I search for a workaround.

**Comment by wthrowe** [comment]
clang-6.0.1 with libstdc++-10.2.0 rejects the expression `std::variant<std::string>{}`.  (The contained type has to be sufficiently complicated.  Probably something like non-trivially-copyable, but I haven't tried to narrow it down.)

There's no way this is going to work.  Marking dependent on compiler support, but any dev should feel free to close if they feel that is more appropriate.

**Comment by nilsvu** [comment]
From the comments in the issue you link it sounds like `std::variant` is pretty much unusable for clang-6 with libstdc++. Should we just drop support for clang-6 altogether (maybe even clang-7, released Sep 2018)? Or do we rely on clang-6 anywhere?

**Comment by nilsvu** [comment]
> From the comments in the issue you link it sounds like std::variant is pretty much unusable for clang-6 with libstdc++. Should we just drop support for clang-6 altogether (maybe even clang-7, released Sep 2018)? Or do we rely on clang-6 anywhere?

@nilsdeppe @kidder do you have thoughts on this?

**Comment by nilsdeppe** [comment]
Clang 8 was released March, 2019. That seems a bit cutting edge to require, so I think we should require clang 7. I'm happy dropping clang 6 and replacing it in CI with clang 7. If bumping to clang 8 is necessary to get this to work I'll have to reconsider, but right now I think requiring clang 8 is very strict

**Comment by wthrowe** [comment]
Rebased for changes to supported compilers.

**Review by nilsdeppe — DISMISSED** [review]

**Review by nilsvu — DISMISSED** [review]

**Comment by nilsvu** [comment]
@wthrowe gcc-7 doesn't approve

**Comment by wthrowe** [comment]
It's wrong.  I'll add some pragmas.

**Review by nilsvu — APPROVED** [review]
I think it would be good to move `create_from_yaml` specializations for `std` types to separate files so `ParseOptions.hpp` doesn't grow indefinitely. @moxcodes already does that for `std::complex` (buried in #2608). If you feel like doing that now for this PR, I'm happy for you to move the code and squash directly. Also fine with me to defer that.

**Review by nilsdeppe — APPROVED** [review]

**Comment by wthrowe** [comment]
The current design pattern was devised to minimize the number of required includes of ParseOptions.hpp.  The contents of a `create_from_yaml` struct usually need ParseOptions.hpp to be usable, so we wanted those structs to be included only when parsing might actually happen.

But, since the addition of the template parameter on `create_from_yaml::create` I don't think this applies anymore.  The calls to `parse_as` should only be compiled when `create` is instantiated, which should only happen when the option parser is being used.

However, in this case the code does more than specialize `create_from_yaml`.  It also specializes `yaml_type`, which is not a public interface exposed in `Options.hpp`, so splitting it out is not trivial.  This is the same issue causing #2654.

**Pull request merged**
