### PR TITLE
Allow overwriting H5 tensor data, add `--force` option to transform-vol CLI

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Add `--force` option to `spectre transform-vol`. Needs capability to overwrite tensor data in H5 files.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
What did you need this for? This seems like it could be catastrophically dangerous...

**Comment by nilsvu** [comment]
Rerunning `transform-vol` and changing the function in between. Of course `--force` is dangerous because it will overwrite data.

**Review by nilsdeppe — APPROVED** [review]

**Comment by knelli2** [comment]
I'm still having reservations about adding this capability. I'd like to discuss this a bit more offline (probably too long for GitHub comments)

**Comment by nilsvu** [comment]
Ready to merge this @knelli2 ?

**Comment by knelli2** [comment]
Yeah. After some consideration, I'm still not a fan of our application allowing overwriting simulation data that could potentially take months to recompute, but `--force` is telling the application that you know better than it so it'll be the users fault.

**Pull request merged**
