### PR TITLE
Fix building with shared libs on develop

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

We have circular dependencies, which are only caught when building with shared libs... Without this I can't build

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by fmahebert — DISMISSED** [review]
Oh I was trying to apply the rules we were discussing in our private conversations, but I didn't think to look for circular deps, sorry :-/

**Review by kidder — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
@fmahebert nothing to apologize for! One of the big reasons for going in that direction is to catch and fix all the cyclic dependencies :D

**Comment by nilsdeppe** [comment]
I've noticed some other failures with missing deps so I'll try to fix these as part of this

**Review by kidder — DISMISSED** [review]

**Review by fmahebert — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
Okay, fixed another issue with `ExportCoordinates` and shared libs, and converted the clang-9-debug CI build to use shared libs. Hopefully that'll help us catch most issues for now. Python bindings don't work with shared libs yet, but I'd rather have the core C++ working with shared libs than nothing at all

**Review by kidder — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
@kidder sorry, added another commit that allows each test to timeout twice so that if we hit a random timeout we don't need to rerun all builds...

**Comment by nilsdeppe** [comment]
I pushed another commit that fixes develop with `add_spectre_library` and `INTERFACE` keyword. There was a "conflict" between two PRs that didn't get caught

**Review by kidder — APPROVED** [review]

**Review by moxcodes — APPROVED** [review]
Ah, good, I was just wondering how to fix the `INTERFACE` thing.

**Comment by nilsdeppe** [comment]
@fmahebert if you have any additional comments I'm happy to address them in a follow-up PR, just wanted to revive develop :)

**Pull request merged**
