### PR TITLE
Update spectre doi author list

### PR DESCRIPTION
**Pull request by kidder**
## Proposed changes

Promote Francois Hebert and Jordon Moxon to core developers.

Add Jason Guo, Yoonsoo Kim, Kyle Nelli, and Niko Wittek as contributors.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by kidder** [comment]
@erfz @nikwit @yoonso0-0 @knelli2 please check that your data is correct, and if you have an Orcid number please add a comment

**Comment by knelli2** [comment]
Orcid: 0000-0003-2426-8768

**Comment by knelli2** [comment]
Also, could you add my middle initial: `Nelli, Kyle C.` . Thanks!

**Comment by erfz** [comment]
Could you add my middle initial as well: `Guo, Jason S.`? Thanks.

**Comment by nikwit** [comment]
Thanks.

Please also add my initial: Wittek, Nikolas A.

Orcid number: 0000-0001-8575-5450

**Comment by yoonso0-0** [comment]
Checked everything's correct. Thanks!

**Comment by kidder** [comment]
@knelli2 @erfz @nikwit  please approve the PR if I have correctly updated your entry

**Review by nikwit — DISMISSED** [review]

**Review by knelli2 — DISMISSED** [review]

**Review by erfz — DISMISSED** [review]

**Review by wthrowe — DISMISSED** [review]

**Review by nilsvu — DISMISSED** [review]

**Review by wthrowe — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
