### PR TITLE
Build Benchmark executable on CI

### LINKED ISSUE #2015: Revive testing Benchmark.cpp
# Bug reports:

### Expected behavior:

The code in Benchmark.cpp should be tested on GitHub actions

### Current behavior:

It isn't

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Closes #2015

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I think this just needs to link the `Informer` lib into `Benchmark` :)

**Comment by nilsdeppe** [comment]
I think we want to ignore (using compiler pragmas) the warning you get because some versions of benchmark require that semicolon there

**Review by nilsdeppe — APPROVED** [review]
This looks good to me. I'm not sure why the clang-tidy release check was cancelled or why this is marked in progress.

image

**Review by kidder — APPROVED** [review]

**Comment by nilsvu** [comment]
Looks like the clang-tidy check is the usual boost root find issue, or am I missing something else? Removed the _in progress_ label

**Comment by nilsdeppe** [comment]
Okay, LGTM!

**Pull request merged**
