### PR TITLE
Move time-stepper implementations to cpp files

### PR DESCRIPTION
**Pull request by wthrowe**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
@wthrowe looks like this needs a rebase to deal with some conflicts in the executables :(

**Comment by wthrowe** [comment]
I conflicted with myself, so I can't complain too much.

The Mac issue still needs to be resolved.  (The last commit didn't work.)

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
Talking with @kidder we'll ignore the macOS CI failure until someone can actually reproduce it locally. I don't understand why it thinks that we need Catch instantiations in the source tree. This might be related to that we can include test files in the source tree, but that still doesn't make any sense to me either...

**Comment by nilsvu** [comment]
Ugh now I can't build `DataStructuresHelpers` anymore :(

**Comment by kidder** [comment]
yes, but it builds fine on my macs and the CI error makes no sense so it is unfair to hold up something that is impossible to debug

**Comment by nilsvu** [comment]
Well you could have asked me to debug before merging.

**Comment by wthrowe** [comment]
For the record, I didn't want this merged in it's current state.

**Comment by nilsdeppe** [comment]
How should we handle that clearly in the future? Would it make sense to mark the PR as in-progress if you don't want it merged? My interpretation of the comment that the macOS build failed was "In case we care, it doesn't work." I've been under the impression that we don't require macOS to pass, and that macOS isn't officially supported because debugging those issues can be very challenging if you don't have access to a mac. At least back in the Travis-CI days when we had mac builds we agreed that macOS was not required to pass to merge a PR. I don't remember any discussion changing that. We even didn't have macOS in CI for a very long time.

**Comment by wthrowe** [comment]
"In progress" means "don't want reviews".  That wasn't the case here.

I'm not sure how I can make things clearer than explicitly stating that there is an issue that needs to be resolved and that there is a non-working commit.  It's not like you failed to read the comment before merging, because you responded directly to it.

**Pull request merged**
