### PR TITLE
Turn off fail-fast in Tests.yaml.

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes

Sometimes when tests fail, it is useful to see whether or not they fail only on some compilers, to help with debugging.

This change makes the CI unit tests all run, even if some of them fail.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
Thanks for factoring out this change into a separate PR.

I can see how turning off fail-fast can be useful to check whether an issue is only with a particular compiler, or with a random-value test. However, this change would increase CI build times in general and I'm not sure whether we can afford that, with CI builds already queuing up a bit. Furthermore, people should check that CI builds pass on their own forks anyway, and only open a PR once they do, instead of debugging CI issues in a PR. It's easy to push to a new branch to run the CI checks and debug them. We could add a note to the documentation suggesting to disable fail-fast to help debugging.

That said, the increase in CI build times from disabling fail-fast might not be dramatic, because builds that fail on all compilers would probably fail around the same time anyway, but I find it difficult to predict. In particular, I have often seen the single CI build with disabled PCH (that doesn't build `RunTests`) catch obvious compiler errors and cancel the CI build early, thus saving a lot of time. I see two options here:

1. Disable fail-fast and see how much it impacts CI build times. Re-enable it if we find CI build queue up too much.
2. Add a note to the docs suggesting to disable `fail-fast` for debugging CI builds on forks.

I'm in favor of 2. to keep CI build times down and to encourage debugging CI issues on forks. What do you think?

**Review by geoffrey4444 — APPROVED** [review]

**Comment by markscheel** [comment]
@nilsleiffischer For the error that prompted me to make this PR, I was unable to reproduce it locally for a while, so I really wanted the information of exactly which compilers succeed and which compilers fail.

I agree if this PR slows down CI for everyone then we should revert it.  Let's see what others think.

**Comment by nilsvu** [comment]
@markscheel To clarify: I'm suggesting to debug CI issues that you can't reproduce locally by pushing to a new branch on your fork, so CI runs on your fork instead of running on the main SXS repo. Then you can push to that branch as much as you want without filling up the queue on the main repo, and you can push a commit that disables fail-fast.

**Comment by wthrowe** [comment]
Do we ever actually have anything waiting in our queue?

I don't know exactly what our setup is, but I think we have 60 runners, which is enough to handle 3-4 PRs in parallel.

**Comment by nilsvu** [comment]
@wthrowe We have 20 runners: https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits

**Comment by wthrowe** [comment]
I think we're "Team" tier.  @kidder?

**Comment by kidder** [comment]
@wthrowe @nilsleiffischer yes, sxs-collaboration is a GitHub team

**Comment by nilsvu** [comment]
Oh that's nice!

**Comment by markscheel** [comment]
I'm happy to close this PR and turn of fail-fast in my fork when needed, or to keep this PR. Whatever everyone else wants.

**Comment by wthrowe** [comment]
@nilsleiffischer Do you still object to this change?

**Comment by nilsvu** [comment]
I don't object, my preference would be to keep fast-fail enabled, but we can try this if others think it's useful.

**Comment by kidder** [comment]
I would like to try this out as I am not that worried about a slowdown of the CI

**Comment by nilsdeppe** [comment]
I'd also like to try this

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Review by nilsvu — APPROVED** [review]
Ok sure!

**Pull request merged**
