### PR TITLE
Add some logging to Schwarz solver reductions

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Output a message when a reduction completes to give the user an idea what's going on in an elliptic solve.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@erfz This code should give you an idea how the reduction logging works in action. Feel free to look through the code and comment if anything is unclear.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsvu** [comment]
Rebased since this has been open for a while. @kidder could you take over for @erfz?

**Comment by nilsvu** [comment]
Rebased again on develop

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
Restarted CI because the failure from #3011 showed up

**Comment by nilsvu** [comment]
Rebased on #3018 to get CI to pass

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
