### PR TITLE
Assert LGL meshes in dg::mortar_mesh, fixes #869

### LINKED ISSUE #869: Add ASSERT to dg::mortar_mesh
# Bug reports:

An `ASSERT` should check that the input is only LGL.

### PR DESCRIPTION
**Pull request by nilsvu**
### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by fmahebert** [comment]
I'm happy with this. But a thought: if we want to check that meshes are LGL elsewhere in the code (and presumably we do?), then perhaps this could be implemented as a standalone helper function `bool mesh_is_lgl(const Mesh<Dim>& mesh)`.

**Review by kidder — DISMISSED** [review]
If this appears again, then yes, do @fmahebert suggestion

**Comment by kidder** [comment]
@nilsleiffischer there is a IWYU failure

**Comment by nilsvu** [comment]
fixed @kidder

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
@nilsdeppe @wthrowe this is short

**Review by nilsdeppe — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
