### PR TITLE
Optionally bootstrap missing Py dependencies

### LINKED ISSUE #4124: Unit.Options.Python.ExtractInputSourceYAMLFromH5 fails
# Bug reports:

### Expected behavior:
It passes

### Current behavior:

Note that the test name should also be updated from `YAML` to `Yaml`

```
 Start 1422: Unit.Options.Python.ExtractInputSourceYAMLFromH5
 1/1 Test #1422: Unit.Options.Python.ExtractInputSourceYAMLFromH5 ...***Failed    0.12 sec
 test_read_input_source_from_h5 (__main__.TestExtractInputSourceYAMLFromH5) ... FAIL

 ======================================================================
 FAIL: test_read_input_source_from_h5 (__main__.TestExtractInputSourceYAMLFromH5)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
 File "/home/nils/SpECTRE/spectre/tests/Unit/Options/Python/Test_ExtractInputSourceYamlFromH5.py", line 39, in test_read_input_source_from_h5
 self.assertEqual(input_source, expected_input_source_yaml)
 AssertionError: b'# Distributed under the MIT License.\n#[4698 chars]se\n' != '# Distributed under the MIT License.\n# [4697 chars]se\n'
```
I'm using python 3.9.7. This looks like a string encoding issue to me. My OS is Ubuntu 20.10.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/BuildInfo.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

When the optional `BOOTSTRAP_PY_DEPS` CMake flag is enabled, missing Python dependencies are installed to `${CMAKE_BINARY_DIR}/lib/python3.X/site-packages`. This is an alternative if the user doesn't want to bother installing the dependencies themselves, e.g. on a cluster. If there's a problem with packages like h5py, numpy or scipy the user can/should still install them themselves to make sure they use the correct HDF5, BLAS, etc.

Enabling this on Wheeler, Ocean and Minerva. The other clusters have setup scripts that install the dependencies in the user directory anyway.

This also fixes #4124 on Wheeler.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
I tested this on Wheeler. @geoffrey4444 could you make sure this works on Ocean please? Just build and run unit tests.

**Comment by nilsdeppe** [comment]
Tests pass on Ocean, fail on wheeler:
```
Filters: "Unit.PointwiseFunctions.EquationsOfState.DarkEnergyFluid"
Traceback (most recent call last):
  File
  "/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/__init__.py",
  line 23, in <module>
      from . import multiarray
        File
        "/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/multiarray.py",
        line 10, in <module>
            from . import overrides
              File
              "/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/overrides.py",
              line 6, in <module>
                  from numpy.core._multiarray_umath import (
                  ImportError:
                  /home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so:
                  undefined symbol: PyObject_SelfIter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
  "/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/__init__.py",
  line 140, in <module>
      from . import core
        File
  "/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/__init__.py",
  line 49, in <module>
      raise ImportError(msg)
      ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from ""
    * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was:
/home/nils/ds09/spectre/spectre_nils/build_clang/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so:
undefined symbol: PyObject_SelfIter
```

**Comment by nilsvu** [comment]
Edited the wheeler env file to use the new miniconda module (thanks @nilsdeppe!). Could you try again please? Tests build and pass for me.

**Review by nilsdeppe — APPROVED** [review]
I've run the unit tests on both Wheeler and Ocean and they pass other than `Unit.Visualization.Python.Render1D (Timeout)`

**Review by geoffrey4444 — APPROVED** [review]

**Pull request merged**
