### PR TITLE
Set up ghost zones for MC

### PR DESCRIPTION
**Pull request by ffoucart**
## Proposed changes

Builds infrastructure for the use of GZ within the MC code.

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by ffoucart** [comment]
Depends on #5907

**Comment by ffoucart** [comment]
Start handling ghost zones by:
(1) Getting GZ data for density, temperature, Ye as input to the MC code
(2) Assuming that neutrino emission/absorption/scattering are computed on an extended mesh with GZ
(3) Assuming that coupling to the fluid is compute on an extended mesh
As part of this change, the proper volume term going in the calculation of the emission rate has been moved to the emitpacket function.

This does not allow packets to move from cell to cell yet (#5998  will be needed for that)

**Comment by ffoucart** [comment]
Rebased against 5907 and 5998. Should now be up to date with the current state of develop and ready for full review.

**Review by kidder — APPROVED** [review]
This seems fine to me.

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
