### PR TITLE
Fix bug in `test_copy_semantics` where constructor instead of assignment operator is called

### PR DESCRIPTION
**Pull request by nikwit**
I think the test helper is supposed to check both copy assignment and copy construction but it currently does not because `T b = a` does not call the assignment operator, see https://stackoverflow.com/questions/29154814/when-is-the-copy-assignment-operator-called

### CODE REVIEW

**Comment by wthrowe** [comment]
I agree that it is a bug, but your fix does not compile.

**Comment by nikwit** [comment]
yeah, I should not create PRs from the browser at midnight, sorry^^ 
The only other way I can think of is
```
T b = a;
b = a;
```
However, this will fail to find if the copy assignment operator forgets to copy something over as it is already correctly initialized from the copy constructor. Should we restrict the test to classes that have a default constructor? Or is there a hacky way to create an object in an invalid state, maybe `std::any`?

**Comment by nikwit** [comment]
turns out there were only two exceptions which probably should have a default constructor/be pupable. So the test now requires that the class is default constructible.

**Review by wthrowe — APPROVED** [review]
I think that is a reasonable requirement.

**Pull request merged**
