### PR TITLE
Split UpdateU action

### PR DESCRIPTION
**Pull request by wthrowe**
Recording data without actually taking a step will be necessary for
self-starting.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — DISMISSED** [review]
Docs are rendered at: http://gh.nilsdeppe.com/spectre/pr_893/

**Review by fmahebert — COMMENTED** [review]
I would find the documentation more useful if it briefly described what `Record data...` actually means. Specifically, what data is being recorded, and how/where?

Maybe this is a silly question, but as someone only partially familiar with the actions, I did not find this obvious.

**Comment by wthrowe** [comment]
Something like "Records the time derivative of the variables in the time-stepper history."?

(This isn't quire true (the recorded quantity may not be exactly the time derivative), but it's no more sloppy than most of the other documentation and naming surrounding this stuff.)  I'm also open to changing the word "record" in the class name and documentation if people don't like it.

**Comment by wthrowe** [comment]
Er, make that "Records the variables and their time derivatives in the time-stepper history."

**Comment by nilsdeppe** [comment]
I like the word "record" because it doesn't conflict with any other concepts in C++ or the code (at least that I can think of). "store" or "save" might have the implication that something is written to disk.

**Comment by wthrowe** [comment]
Documentation updated.

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]
I think this is clearer 👍

**Comment by kidder** [comment]
travis failures are timeouts

**Pull request merged**
