### PR TITLE
Increase timeout for Schwarzschild input file test

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

The test occasionally timed out on CI.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
Labeling `priority` to restore CI on develop, so we can publish the June release.

**Review by moxcodes — APPROVED** [review]
Seems fine -- perhaps a bit long of a test if we're trying to keep test times down, but I have no real objections.

**Comment by nilsvu** [comment]
yea it usually takes only 3-5s on my machine, so not sure what causes the timeout 🤷‍♂️

**Review by geoffrey4444 — APPROVED** [review]

**Comment by nilsdeppe** [comment]
I think as long as this length of tests doesn't start becoming the norm it's okay. We do need some reasonably resolved and thorough integration tests, but SpEC has some tests that are 20 min on 4 cores, which is way too long.

**Pull request merged**
