### PR TITLE
Pin macOS python version on CI

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

Pin version to 3.10

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
Oh sorry I haven't seen this PR before opening #4356. Let's see how that one does :)

**Comment by knelli2** [comment]
@nilsvu No worries! In my testing I wound up also having to use `actions/setup-python@v4`, but I found that I also had to explicitly specify the python executable in cmake to be 3.10 like I did here, otherwise it would still find 3.11

**Comment by knelli2** [comment]
Ok got everything to pass now. @nilsvu If you're happy with this solution, shall we just use this?

**Comment by nilsvu** [comment]
I think I found the root cause of the problem. See #4356.

**Comment by knelli2** [comment]
Closing because this issue is fixed by #4356.

**Comment by nilsvu** [comment]
Thanks for figuring this out together 👍

**Pull request closed without merging**
