### PR TITLE
Fix PCH dependencies

### PR DESCRIPTION
**Pull request by nilsvu**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@nilsdeppe could you try this? I'm still testing it on a bunch of builds in the container, but I think this restores the same dependency handling as before, just propagating the flags now.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
This works on my machine with both Ninja and Make. Thanks for the quick fix!

**Comment by nilsvu** [comment]
Turns out the fix didn't correctly propagate the flags, adjusted slightly. Please make sure this fixes your issue before merging, since I can't reproduce it.

**Review by nilsdeppe — APPROVED** [review]
Still works on my machine

**Review by kidder — APPROVED** [review]

**Pull request merged**
