### PR TITLE
Remove single-extent volume data in test

### LINKED ISSUE #3242: Test_VolumeDataReaderAlgorithm2D and 3D tries to write single-extent volume data
# Bug reports:

### Expected behavior:

The volume data should have at least 2 extents in each dimension, otherwise we cannot write connectivity.

### Current behavior:

The extents are things like `{2,1,1}` which we cannot process in ParaView anyway. Supporting such behavior would require completely redesigning the way we do volume data IO.

Note:
I need this fixed in order to enable compression in HDF5 (reduces volume data file size by up to 10x), so getting this fixed sooner rather than later would be good. If that can't be done I can comment out the 2d and 3d tests until this issue gets fixed.

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Closes #3242.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@nilsdeppe this should get the test working with your HDF5 compression code. In the long run we should probably look into supporting single-extent volume data if we support DG Gauss points. Perhaps this can be solved in the context of https://github.com/sxs-collaboration/spectre/issues/3337.

**Comment by nilsdeppe** [comment]
Thanks for doing this! It looks like the build is unhappy.

The only way I can think of supporting single point elements is in post-processing. You'd have to build up the connectivity across all the volume files, which I have no idea how easy it is to do. Supporting the Lagrange interpolation should be easier if there's a way to get XDMF to handle it

**Comment by nilsvu** [comment]
@nilsdeppe the build fails due to https://github.com/sxs-collaboration/spectre/pull/3334, you can go ahead and merge that or we wait for Will to do it

**Review by nilsdeppe — APPROVED** [review]
ah okay, thanks!

**Review by kidder — APPROVED** [review]

**Pull request merged**
