### PR TITLE
Make db::mutate_apply and db::mutate consistent

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Make the order of arguments the same. Choosing the same order as `std::apply`.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — APPROVED** [review]
Thank you.  That was always annoying.

Merging now because this is going to conflict with everything.

**Comment by nilsdeppe** [comment]
The argument order is backwards to our standard... `gsl::not_null` should be first.

**Comment by nilsvu** [comment]
I chose consistency with `std::apply` here. Also I think for `db::mutate_apply` this order was chosen because the lambda can be specified as a template parameter instead.

**Comment by nilsdeppe** [comment]
Okay, that's reasonable. Thanks for the explanation!

**Pull request merged**
