### PR TITLE
Support segments in GenerateXdmf

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Also refactor to use Python's XML engine. This allows inserting grids into the XML tree, which helps with supporting H5 files with different observations.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
There seem to be actual failures in CI here

**Comment by nilsvu** [comment]
Ugh yea Py 3.7 doesn't preserve attribute order in XML (`<Tag Arg1="1" Arg2="2">` vs `<Tag Arg2="2" Arg1="1">`). Skipped the test in Py 3.7.

**Review by nilsdeppe — DISMISSED** [review]
LGTM, though there's one remaning CI failure that `ET.canonicalize` doesn't exist. My guess is this is some version thing with `ET`

**Comment by nilsvu** [comment]
Fixed the Py version check

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
CI failure is unrelated timeout.

**Pull request merged**
