### PR TITLE
Add GitHub workflow for continuous integration

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

These checks run on the GitHub Actions infrastructure instead of Travis. They perform the same tests that currently run on Travis except for unit tests, with the purpose of trying GitHub Actions as a potential replacement for Travis. You can take a look at an example PR at https://github.com/nilsleiffischer/spectre/pull/1.

I opened #1802 to discuss GitHub Actions vs Travis in general, so we can keep this PR focused on the code changes.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
Can you please close this until you actually have a fully working implementation? This PR seems a bit premature.

**Comment by nilsdeppe** [comment]
Actually, rather than letting this eat up travis resources, I'm closing it now.

**Comment by nilsdeppe** [comment]
There were 3 running jobs taking up travis resources. Please debug your code before submitting a PR. That would also help speed up wait times ;)

**Comment by nilsvu** [comment]
Right, I was testing on my fork and this PR got updated. Unit tests are working fine now with the full build matrix, and it was surprisingly easy to set up.

**Pull request closed without merging**
