### PR TITLE
Debug test failures in github actions

### PR DESCRIPTION
**Pull request by geoffrey4444**
## Proposed changes

I can’t reproduce some test failures locally, so this draft PR will help me debug them. Once the issues are fixed, I will close this draft PR.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
For my understanding, what advantage does the draft PR have over just having the code build on your fork?

**Comment by geoffrey4444** [comment]
> For my understanding, what advantage does the draft PR have over just having the code build on your fork?

So I can monitor the tests from the github app on my phone

**Comment by nilsdeppe** [comment]
and this is not possible with builds on your fork?...

**Comment by geoffrey4444** [comment]
> and this is not possible with builds on your fork?...

Not as far as I’ve been able to determine, or I’d have just done that

**Comment by nilsdeppe** [comment]
Could you please build this on your fork only so as not to take resources away from PRs that are actually going to be merged?

**Comment by geoffrey4444** [comment]
Sure! Didn't realize this was holding up other checks @nilsdeppe

**Pull request closed without merging**
