### PR TITLE
Fix documentation with recent versions of doxygen

### LINKED ISSUE #5490: Doxygen 1.9.7 or later creates empty documentation html index
# Bug reports:

### Expected behavior:

Documentation should build an html index with associated entries filled in as desired.

### Current behavior:

When running with Doxygen 1.9.7 or more recent versions, the html index is generated and constructs entries, but these entries are empty.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/BuildInfo.txt` or
add its contents here.

[BuildInfo.txt](https://github.com/sxs-collaboration/spectre/files/12704073/BuildInfo.txt)

# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### PR DESCRIPTION
**Pull request by kidder**
## Proposed changes

Fix #5490 

The first commit just updates the versions of files we use from the Doxygen Awesome CSS theme

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by kidder** [comment]
@wthrowe @ncorsobh please check that this works for you.  I have not fixed all doxygen warnings for all versions; version 1.11.0 has no warnings for me.

**Review by nilsvu — APPROVED** [review]
LGTM overall, haven't tested it though

**Review by wthrowe — APPROVED** [review]
Seems to work with doxygen 1.12.0.  I get a bunch of nonsensical warnings, but that's not a blocker.  Example:
```
/home/wthrowe/tmp/host-docs/source/src/Evolution/Executables/Cce/KleinGordonCharacteristicExtract.hpp:125: warning: no uniquely matching class member found for 
  typedef EvolutionMetavars::factory_creation::tmpl::map< tmpl::pair< LtsTimeStepper, TimeSteppers::lts_time_steppers >, tmpl::pair< StepChooser< StepChooserUse::LtsStep >, cce_step_choosers >, tmpl::pair< StepChooser< StepChooserUse::Slab >, StepChoosers::standard_slab_choosers< system, local_time_stepping, false > >, tmpl::pair< TimeSequence< double >, TimeSequences::all_time_sequences< double > >, tmpl::pair< TimeSequence< std::uint64_t >, TimeSequences::all_time_sequences< std::uint64_t > >, tmpl::pair< Event, tmpl::list< Cce::Events::ObserveFields, Cce::Events::ObserveTimeStep > >, tmpl::pair< Trigger, tmpl::append< Triggers::logical_triggers, Triggers::time_triggers > > > factory_classes
Possible candidates:
  'T std::map::map(T... args)' at line 32548 of file /home/wthrowe/tmp/host-docs/source/docs/config/cppreference-doxygen-web.tag.xml
  'T std::pmr::map::map(T... args)' at line 37437 of file /home/wthrowe/tmp/host-docs/source/docs/config/cppreference-doxygen-web.tag.xml
```

**Comment by nilsvu** [comment]
Works on CI

**Pull request merged**
