### PR TITLE
Add elasticity executable

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Adds the first elliptic executable for the Elasticity system.

Depends on:
- [x] #1915 
- [x] #2077 
- [x] #2290 

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
@geoffrey4444 could you review this one? And @sxs-collaboration/spectre-core-devs perhaps one of you since it adds a new executable?

**Comment by nilsvu** [comment]
I factored out the three preparation commits to #2290, but if you prefer we can keep them here and I close #2290.

**Review by kidder — DISMISSED** [review]

**Comment by nilsvu** [comment]
@geoffrey4444 could you review this when you get the chance?

**Comment by nilsvu** [comment]
@geoffrey4444 please take a look at this PR

**Review by geoffrey4444 — DISMISSED** [review]
I took a quick look, and everything looks reasonable to me. I didn't try to actually run the executable yet, but looking forward to trying it

**Comment by nilsvu** [comment]
Thanks @geoffrey4444! I rebased on latest develop to run CI again just to be sure

**Comment by nilsvu** [comment]
CI passes on latest develop, seems ready to go @kidder. Thanks for reviewing @kidder and @geoffrey4444 !

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
