### PR TITLE
Remove ability to override functions of time

### PR DESCRIPTION
**Pull request by kidder**
The control system is working to a level where importing a function of time from a spec evolution no longer makes sense.  The differences between the spacetime evolution of spec and spectre can no longer be disentangled from the control system differences.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by kidder** [comment]
marked as in progress until @geoffrey4444 and @knelli2 no longer fell the need to override FunctionsOfTime

**Comment by knelli2** [comment]
@kidder I talked with @geoffrey4444 and we are confident now that we won't be using this anymore. If there comes a time where we, for some reason, need this, we can always revert it.

**Comment by kidder** [comment]
@knelli2 rebased and removed in-progress label

**Review by knelli2 — APPROVED** [review]
Thank you for doing this! It'll make my changes to the measurement timescales a bit easier

**Comment by knelli2** [comment]
@sxs-collaboration/spectre-core-devs Do any of you want to look at this? If not, I'll merge tonight because it conflicts with my measurement expiration time changes.

**Comment by nilsdeppe** [comment]
Let's get it merged :) You are the only one really effected by this :D

**Comment by knelli2** [comment]
Ok then in that case, I'll merge now

**Pull request merged**
