### PR TITLE
Add option for lmax_factor to reduction script

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

This is useful for conversions that have unusually high aliasing.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by markscheel — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]
Code looks fine.

For my understanding (because this seems surprising to me): what kind of scenario requires bumping l_max by more than 2x? are the equations extremely nonlinear? is this a sign of something going wrong?

**Comment by moxcodes** [comment]
@fmahebert it's a good question. The equations are pretty nonlinear, with several tensor products and determinants fed into a logarithm, which is then later multiplied by several other things, so I'm not immediately surprised that we might get modes scaling the ladder pretty quickly.

We're seeing that the errors between SpEC and SpECTRE conversions on certain runs start spiking near merger, with the highest modes getting the largest differences. Given that the worst behavior was at the highest modes (like l_max ~16), I think the first culprit is aliasing. If bumping the factor doesn't help, we'll have to investigate more carefully if there's something subtle going wrong in the nonlinear terms of the calculation.

**Comment by fmahebert** [comment]
@moxcodes Thanks for the explanation, that was helpful. Hopefully this l_max bump helps the conversions!

**Comment by moxcodes** [comment]
@markscheel and I examined the results from taking it to a factor of 3 for SpECTRE and SpEC, and it is sufficient to avoid large errors for the entire waveform on an example test case.

**Review by kidder — APPROVED** [review]

**Pull request merged**
