### PR TITLE
Get Pypp tests working with more python configs

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

With python 3.6 on some systems there are FPEs inside the python libraries (I
don't know, seems terrifying). Disabling FPEs resolves the issue and the tests
then actually pass.

@osheamonn @kidder @wthrowe could you look at this when you get? It's short and will make my life a bit easier :)

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### CODE REVIEW

**Review by kidder — COMMENTED** [review]
cant' we turn off FPEs only when python is being called?
I don't like turning them off for entire test cases

**Comment by nilsdeppe** [comment]
Sure, but doesn't really make a difference. `NaN != NaN` so all checks will fail

**Comment by nilsdeppe** [comment]
Okay, updated to the minimal scoped FPE exception disabling :)

**Review by kidder — APPROVED** [review]

**Review by osheamonn — APPROVED** [review]
I'd only tested this with python 2.7 and 3.5 so this is pretty bizarre to me but if disabling FPE's works then I approve.

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
