### PR TITLE
Remove the wheeler clang env file

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Intel MPI claims not to work with clang. I have not tested if it does and so for
now it's best to just remove the env file.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
A thought: I imagine we'll eventually want to support clang on wheeler again (at least I'd like to use clang). What do you think about making a `inactive` or `no_longer_used` directory inside `support/Environments` and move the wheeler clang env file there instead of deleting it?

**Comment by wthrowe** [comment]
Is the git history not sufficient for that?

**Comment by knelli2** [comment]
I suppose it is. I don't feel strongly either way. Was just a suggestion.

**Comment by nilsdeppe** [comment]
I guess I don't really see a reason to keep around things that don't work, and I have no plans to figure out Clang on Wheeler :shrug:

**Comment by wthrowe** [comment]
Obsoleted by #4230?

**Comment by knelli2** [comment]
Yes

**Pull request closed without merging**
