### PR TITLE
Make types explicit in DH test, remove redundant GH tests

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

- Make types explicit instead of using `db::item_type` in the DH test
- Reduce code duplication in DH test (this is the vast majority of this PR and basically just deletes code because it was redundant with the python tests).

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsdeppe** [comment]
Marking in progress because I'm going to see if I can greatly simplify the review process by changing the order of some commits on my branch (think reviewing 500 lines instead of 3000)

**Review by moxcodes — APPROVED** [review]
Looks fine. On a cursory look through, I guess these tests used to compute just one part of what the src function computes and pass in some arguments as zeros to get it to compute only that term from the function? I agree, then, that ~4 iterations of the python tests is functionally very close to the removed tests.

**Comment by nilsdeppe** [comment]
@moxcodes yes that's exactly what it did. Additionally, they were just reimplementations of the C++ code and we've generally found that to be not the most trustworthy test. While the python tests are also susceptible to having the same typos that the C++ code does, it's at least reduced because of the different syntax :)

**Review by geoffrey4444 — APPROVED** [review]
Thanks for doing this!

**Review by kidder — APPROVED** [review]

**Pull request merged**
