### PR TITLE
Pass cache, array_index, component to events registration, minor fixes

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Make the events registration function consistent with the call operator and the is_ready function, giving it access to the same information. Also fix a few minor things in events.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by wthrowe** [comment]
What do you want these arguments for?  The other functions use them for communication, but I don't think there should be any communication done in this function.

**Comment by nilsvu** [comment]
@wthrowe I want to get the element ID, e.g. to register only the element that contains a particular point for observations (when the domain is not time-dependent). I can't get the element ID out of the DataBox, because the registration mechanism around `registration_list` in the metavars also instantiates the function for an empty DataBox (not sure why, but it's probably right). But the element ID is available through the array index, and the domain through the global cache, and both get passed to the call operator and is_ready anyway, so I thought it makes sense to make the three functions consistent.

**Comment by wthrowe** [comment]
It sounds like a bug if we're trying to register an uninitialized element.

**Comment by nilsvu** [comment]
🤷‍♂️ we currently instantiate all simple actions for an empty DataBox, so it might be related to that. Passing the available info to the registration function seems right to me nevertheless, don't you agree?

**Comment by wthrowe** [comment]
This isn't called from a simple action, is it? RegisterEventsWithObservers is an iterable action.

I do not agree about making arguments the same.  The GlobalCache in particular is pretty much just for communication these days, so we shouldn't pass it to functions that are not allowed to communicate.

**Comment by nilsvu** [comment]
The culprit is `perform_registration_or_deregistration_impl` in `Algorithm.hpp` being called for all DataBox variants. I just want to get the element ID in the function, do you have another suggestion?

**Comment by wthrowe** [comment]
How about
```c++
if constexpr (db::tag_is_retrievable_v<T...>) {
  ...;
} else {
  ERROR(...);
}
```

**Comment by nilsvu** [comment]
Ok I'll go with that for now.

**Pull request closed without merging**
