### PR TITLE
Rename StrahlkorperDatabox to Tags

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Tags is the name we've used everywhere else, so this is for consistency.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Comment by wthrowe** [comment]
Travis failures are legitimate.  (clang-tidy)

**Comment by nilsdeppe** [comment]
Fixed and rebased on develop

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
@wthrowe this is ready

**Review by wthrowe — APPROVED** [review]

**Comment by wthrowe** [comment]
Travis failure was one of the usual timeouts.

**Pull request merged**
