### PR TITLE
Move linear solver directory to ParallelAlgorithms

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Moves `NumericalAlgorithms/LinearSolver` to `ParallelAlgorithms/LinearSolver` since it's all parallel components or actions.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by kidder** [comment]
@nilsleiffischer I am sorry this PR wasn't merged when you made it. It is exactly the type of PR we want to encourage for moving code.  I am going to mark it as in progress as it needs a rebase, but when you update it, I will make sure it is merged promptly.

**Comment by nilsvu** [comment]
@kidder Updated this now. Please take a look.

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
travis failure is a timeout

**Comment by nilsvu** [comment]
@nilsdeppe Could you take a look at this please?

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
