### PR TITLE
Rewrite BoundaryHistory to support substeps

### PR DESCRIPTION
**Pull request by wthrowe**
If reviewers prefer, the second and third commits could be moved to a separate PR.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by kidder — COMMENTED** [review]
- I like the rewrite and I have no requested changes.
- clang-tidy has flagged some moves of trivially-copyable type
- gcc11 is not compiling the print function, maybe need a `using ::operator<<;` or an include in the test?

**Comment by wthrowe** [comment]
I can reproduce the gcc 11 problem locally, but I'm not having any luck fixing it.  Adding `using ::operator<<;` immediately before the problematic line and including `Utilities/StdHelpers.hpp` as the first thing in the compilation unit doesn't do anything.  Calling `operator<<` directly either doesn't do anything of gives an error about ambiguity (I think in a different call) depending on exactly how I do it.

**Comment by wthrowe** [comment]
gcc 11 fixed.  Search for `print_stl` if you want to see how.

**Review by kidder — DISMISSED** [review]

**Comment by kidder** [comment]
Hi @wthrowe some of the clang-tidy errors are ones we have fixed in the past 
```
error: parameter 'entry' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls,-warnings-as-errors]
```

**Comment by wthrowe** [comment]
Disabled some checks in a new commit, fixed the rest.  Also deleted an internal function that was never used.

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
I confirmed with @kidder that this can get merged

**Pull request merged**
