### PR TITLE
Enable ParaView on CaltechHPC

### PR DESCRIPTION
**Pull request by nilsvu**
This new environment is the same as before, except switched to Python 3.10 and added a ParaView module. Enables 3D rendering scripts.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
I think there may still be some issues with this because of MPI versions

**Review by knelli2 — CHANGES_REQUESTED** [review]
I think there may still be some issues with this because of MPI versions

**Comment by nilsvu** [comment]
Have you set `ENABLE_PARAVIEW=ON`?

**Comment by knelli2** [comment]
Yes, I pulled this PR to test

**Review by AlexCarpenter46 — APPROVED** [review]
Made a fresh build and did a test run for a headon bbh and used the `spectre render-3d bbh` script and everything worked! Here's the path to the run `/central/groups/sxs/acarp/Run/` in case anyone wants to take a look.

**Comment by nilsvu** [comment]
Thanks for checking @AlexCarpenter46 !

**Review by knelli2 — APPROVED** [review]

**Pull request merged**
