### PR TITLE
Add Pybindings for SpatialDerivOfLapse and SpatialDerivOfShift

### PR DESCRIPTION
**Pull request by ajosorio3**
## Proposed changes

Add Pybindings for SpatialDerivOfLapse and SpatialDerivOfShift

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsvu — DISMISSED** [review]

**Comment by nilsvu** [comment]
Could you fix the typo in the commit message before we merge this?

**Comment by nilsvu** [comment]
The commit messages still has the typo (do `git commit --amend` to edit it, then force-push).

**Comment by nilsvu** [comment]
Also please rebase on the latest code on develop to fix the conflicts

**Comment by ajosorio3** [comment]
I believe it should be good now! Rebased and commit message edited.

**Comment by nilsdeppe** [comment]
@nilsvu could you please take a look?

**Review by nilsvu — APPROVED** [review]

**Pull request merged**
