### PR TITLE
Make some error messages more verbose

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes

Add more verbosity to error messages in a few classes (one commit per class).
I found these enhanced messages useful when debugging.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — COMMENTED** [review]
LGTM but needs a rebase because Domain no longer holds the BCs now

**Comment by markscheel** [comment]
Uh oh (about domain not holding BCs, which will conflict with my cylindrical domain branch).  So I will just put the UniformCylindricalEndcap commit in this PR.

**Comment by markscheel** [comment]
Clang-tidy errors are toms748.  (I wish there was a way to fix that)

**Review by nilsdeppe — APPROVED** [review]
There's a new function in domain creators that returns the BCs, so it's basically a minor refactor :)

**Pull request merged**
