### PR TITLE
Add cartesian_to_spherical routines

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Tensor eager math routines to transform between Cartesian and spherical coordinates.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
Could you please put these in a `cpp` file with instantiations?

**Comment by knelli2** [comment]
What is the intended use for these?

**Comment by nilsvu** [comment]
I added these to use in the extrapolation routines into excision spheres. But I've seen many duplications of this code throughout the repo (search for `atan2`).

When doing this transformation myself I also have to remind myself of the formulae and things like the output range (is phi in [0,2pi] or [-pi,pi], etc).

**Review by knelli2 — APPROVED** [review]
Do you want to go through and replace all the existing implementations with this?

**Comment by nilsvu** [comment]
I started, but then stopped because I didn't want to break anything :D

**Pull request merged**
