### PR TITLE
Replace boost::optional -> std::optional in CoordinateMaps

### PR DESCRIPTION
**Pull request by fmahebert**
## Proposed changes

Replace boost::optional -> std::optional in CoordinateMaps

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

This will fail clang-tidy with
1. The usual complaints from the boost toms rootfinder internals
2. A warning about moving out of a helper function... seems strange to me because I'd expect this to fall under RVO. Is this a false positive or am I missing something?

### CODE REVIEW

**Review by moxcodes — DISMISSED** [review]
Looks good! (except clang-tidy has more to say)

**Comment by fmahebert** [comment]
See the PR description 🙂

**Comment by nilsdeppe** [comment]
I can review this, but here's a quick answer to point 2. I think RVO should eliminate this, but my guess is the `const` is confusing clangtidy. I'd writ it as:
```cpp
  return Matrix{....}
```
This falls under guaranteed copy/move elision while named RVO is non-mandatory even in C++17. I haven't looked into this more because my suggested code change I think makes the easier to read and is a lot less work than figuring out strictly what the standard says all to either `NOLINT` less expressive code or make the change anyway :)

**Review by nilsdeppe — APPROVED** [review]

**Review by moxcodes — APPROVED** [review]

**Comment by kidder** [comment]
ignoring boost clang-tidy error about root-find

**Pull request merged**
