### PR TITLE
Add boundary conditions for radiation transport system

### PR DESCRIPTION
**Pull request by fmahebert**
## Proposed changes

Adds `DirichletAnalytic` and `Periodic` boundary conditions for `RadiationTransport::M1Grey`

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by fmahebert** [comment]
Why would only one of the test configurations encounter a Python ImportError...?

**Comment by kidder** [comment]
That build uses Python 2

**Comment by nilsdeppe** [comment]
You'll need to add the `__init__.py` files into directories (I can look at which ones if that's helpful). You did this for another one of your PRs, Rel hydro maybe?

**Review by nilsdeppe — DISMISSED** [review]
LGTM

**Comment by fmahebert** [comment]
Yeah, I forgot to add these files because my system (Py3) doesn't seem to need them? Oops... adding now. Thanks for the reminder!

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
