### PR TITLE
Add a flag to prevent factory creation of a class

### PR DESCRIPTION
**Pull request by wthrowe**
The factory_classes defined in the metavariables are sometimes used
for dynamic dispatch in addition to actual factory creation.  It is
occasionally useful to be able to dispatch classes that should only be
created programmatically.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by wthrowe** [comment]
Dependent on #3449 because of changes to the `get_*_or_default` interface.

**Review by nilsvu — COMMENTED** [review]
Could you explain your use case for this a bit?

**Comment by wthrowe** [comment]
The event and dense trigger for performing control system measurements.

**Comment by kidder** [comment]
@wthrowe are there updates you want to make to this now that #3449 has been merged?

**Comment by wthrowe** [comment]
I've removed the no-longer-required calls to `CREATE_HAS_STATIC_MEMBER_VARIABLE*` (and the include for that).

**Review by nilsvu — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
