### PR TITLE
Finish removing uses of boost::optional

### PR DESCRIPTION
**Pull request by fmahebert**
## Proposed changes

Each commit removes `boost::optional` from one particular context.

In addition, adds a stream helper for `std::optional` — this was needed by some tests.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I only looked at the code relevant to my PRs, but since it looks like Boost optional is completely gone after this should a check be added to the `tools/FilesTestDef` (or whatever exactly it's called) to prevent including `boost/option*` and maybe also usage of `boost::optional`?

**Comment by fmahebert** [comment]
I thought about that... but I wasn't sure if future code using `boost::optional` again was enough of a sin to make code fail CI. But you/others think it's worth checking for, I'll add it to the PR 🙂

**Comment by nilsdeppe** [comment]
I am not aware of any benefits to `boost::optional` over `std::optional`. There are for unique_ptr (boost can do non-atomic reference counting, which actually can matter)

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — COMMENTED** [review]
LGTM, I think since this removes boost::optional pretty much completely, including serialization and pypp support, having a check to forbid it and request std::optional would be good

**Comment by kidder** [comment]
@fmahebert this has a conflict

**Comment by fmahebert** [comment]
Updated branch to
1. resolve the conflict (@nilsdeppe had already changed one boost optional to std in a recent PR)
2. add check against includes of `boost/optional*` and `boost/none.hpp`
3. remove boost optional headers from CMake boost target

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
Your checks worked ,and found some optional includes :P

**Comment by fmahebert** [comment]
Great success! I'll fix

**Comment by kidder** [comment]
@fmahebert looks like you missed one (or one was added in a recently merged PR)

**Comment by fmahebert** [comment]
Should be fixed.

Added (yet another) commit, to remove boost optional entries from our custom boost IWYU mappings file

**Review by nilsdeppe — DISMISSED** [review]

**Comment by kidder** [comment]
@fmahebert this needs a rebase

**Comment by fmahebert** [comment]
Rebased

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
clang-tidy error is the boost root finder error that we don't know how to deal with

**Pull request merged**
