### PR TITLE
Remove redundant SPECTRE_MACOSX_MIN option

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

This should be just [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html). It's the user's responsibility to set this flag if they don't like CMake's default. We shouldn't interfere.

### Upgrade instructions

If you're building on macOS, check if you are configuring CMake with the `MACOSX_MIN` option. If you do, replace it with the standard [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html). You may also want to use this option if you are getting "built for newer macOS version than being linked" warnings.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@kidder @geoffrey4444 could you take a look at this one? It's a macOS thing

**Comment by nilsdeppe** [comment]
@kidder @geoffrey4444 ping on this

**Comment by kidder** [comment]
This gives me linker warnings 
```
ld: warning: object file (/Users/kidder/ExternalPackages/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/yaml-cpp-develop-qyu5bubb42uus3434oyxcmqy6qky3kc3/lib/libyaml-cpp.a(scantag.cpp.o)) was built for newer macOS version (10.15) than being linked (10.7)
```

**Comment by nilsvu** [comment]
@kidder that's exactly what this PR is for :) Please set `CMAKE_OSX_DEPLOYMENT_TARGET=10.15` instead of `MACOSX_MIN` (see the upgrade instructions).

**Comment by kidder** [comment]
I did that switch and I went from no linking errors to the linking errors I posted...

**Comment by nilsvu** [comment]
I looked into this and understand now what's happening: The issue is that `WrapExecutableLinker.sh` doesn't propagate CMake's build flags when compiling the `InfoAtLink.cpp` file, including the `-mmacosx-version-min` flag (and the `-std=c++17` flag, which I have also had issues with before). That's where the warnings come from. I'll try to fix this, but can't prioritize it right now, so I'll mark this PR "in progress". I think a solution to this will also be needed for #2680.

**Comment by nilsvu** [comment]
This is now fixed. Could you try building this again @kidder and @geoffrey4444?

**Comment by nilsvu** [comment]
Dependent on #2680 again because we reverted #3103.

**Comment by nilsvu** [comment]
Rebased on #2680. This PR gets rid of all "built for newer macOS version than being linked" warnings for me when I set `CMAKE_OSX_DEPLOYMENT_TARGET`. Without the flag, only `SPHEREPACK` complains (maybe a fortran thing). @kidder could you give this a try?

**Comment by nilsvu** [comment]
@kidder and @geoffrey4444 could you confirm this works please? I'm trying to clean up some old PRs.

**Review by geoffrey4444 — DISMISSED** [review]
This worked for me on my M1 Mac, and it got rid of annoying warnings about version mismatches

**Comment by nilsvu** [comment]
@kidder do you want to test this too before we merge?

**Comment by kidder** [comment]
I want it to pass the mac CI before we merge

**Comment by nilsvu** [comment]
@kidder passes CI now! (rebased on #4356)

**Review by kidder — APPROVED** [review]

**Pull request merged**
