### PR TITLE
Fix compiling temperature init with analytic solutions

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

We should test these on CI...

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by isaaclegred** [comment]
The good news is that with runtime initial data this will be tested automatically

**Comment by ermost** [comment]
Thanks for fixing this!

**Review by ermost — APPROVED** [review]

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
This doesn't build...

**Comment by nilsvu** [comment]
Squashed in a fix in RelativisticEuler/SmoothFlow

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
