### PR TITLE
Add TCI option tags for advection subcell

### PR DESCRIPTION
**Pull request by yoonso0-0**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by kidder** [comment]
Are you planning on adding any actual options?  Otherwise I don't think this code is needed...

**Comment by yoonso0-0** [comment]
@kidder Probably not -- do you think it'd be better just delete this rather than leaving as an empty option for subcell?

**Comment by kidder** [comment]
> @kidder Probably not -- do you think it'd be better just delete this rather than leaving as an empty option for subcell?

I would just delete this until there is a reason to specify an option. I see I did add TciOptions in my Burgers draft, but they are unused, so I won't keep them when cleaning up the draft into a PR.  NewtonianEuler does not define a TciOptions

**Comment by yoonso0-0** [comment]
> > @kidder Probably not -- do you think it'd be better just delete this rather than leaving as an empty option for subcell?
> 
> I would just delete this until there is a reason to specify an option. I see I did add TciOptions in my Burgers draft, but they are unused, so I won't keep them when cleaning up the draft into a PR. NewtonianEuler does not define a TciOptions

Okay!

**Comment by nilsdeppe** [comment]
I don't think Newtonian Euler or Burgers had any options. GRMHD does because it's a rather complicated system.

**Pull request closed without merging**
