### PR TITLE
Fix `PYTHONPATH` in Python tests

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Currently a literal `$PYTHONPATH` is added to the `PYTHONPATH`, which doesn't do anything. Change to get the `PYTHONPATH` from the environment. This isn't particularly important since usually modules are picked up from the Python prefix, e.g. when they are installed in a venv, but this fixes an issue with testing a Spack installation.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsvu** [comment]
@nilsdeppe please decide if you want a second review or merge

**Comment by nilsdeppe** [comment]
I personally think we should give people 1 work day to take a look. Yesterday was a holiday in the US. I'll merge either tonight or tomorrow morning if nobody else decides they want to review.

**Comment by nilsvu** [comment]
Ok sounds reasonable. I wish GitHub would add the option for scheduled auto-merge, I vaguely remember seeing that on their roadmap some time.

**Comment by nilsdeppe** [comment]
It's funny you mention that... It was one of your PRs (this one I think) where I was actually thinking it would be really nice to be able to say "Please merge on DATE, TIME if possible." Then it would be clear what the state is, plus then we wouldn't have to go through and check PRs

**Review by kidder — APPROVED** [review]

**Pull request merged**
