### PR TITLE
Make tests for ExtractDatFromH5 in build directory

### LINKED ISSUE #4387: Unit.IO.H5.Python.ExtractDatFromH5 tries to write to the source directory
```
    Start 1405: Unit.IO.H5.Python.ExtractDatFromH5
1/1 Test #1405: Unit.IO.H5.Python.ExtractDatFromH5 ...***Failed    0.23 sec
test_extract_dat_files (__main__.TestExtractDatFromH5) ... ERROR

======================================================================
ERROR: test_extract_dat_files (__main__.TestExtractDatFromH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wthrowe/spectre/tests/Unit/IO/H5/Python/Test_ExtractDatFromH5.py", line 51, in test_extract_dat_files
    extract_dat_files(self.h5_filename, **kwargs_dict)
  File "/home/wthrowe/spectre-gcc-debug-64/bin/python/spectre/IO/H5/ExtractDatFromH5.py", line 26, in extract_dat_files
    os.mkdir(out_dir)
OSError: [Errno 30] Read-only file system: '/home/wthrowe/spectre/tests/Unit/IO/H5/Python/extracted_DatTestData'

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
```

`/home/wthrowe/spectre` is the source directory, `/home/wthrowe/spectre-gcc-debug-64` is the build directory.

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

Previously they were made in the src directory which they shouldn't have been.

Fixes #4387.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — APPROVED** [review]
It passes in my setup, now.

**Review by wthrowe — CHANGES_REQUESTED** [review]
But it's failing on CI: TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by knelli2** [comment]
Ughh python2...

**Review by wthrowe — APPROVED** [review]
Still passes for me.

**Review by nilsvu — APPROVED** [review]

**Comment by nilsvu** [comment]
Failed test is unrelated

**Pull request merged**
