### PR TITLE
Work around a bug in gcc 7.3

### LINKED ISSUE #3206: Internal compiler error when building Test_DgOperator.cpp with gcc 7.3.0
# Bug reports:

### Expected behavior:

Code compiles

### Current behavior:

When building on ocean with gcc 7.3.0, the compilation fails with this error message. I get this error whether using 1, 6, or 20 threads.

~~~
[ 48%] Building CXX object tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/Test_DgOperator.cpp.o
In file included from /home/geoffrey/Codes/spectre/spectre/tests/Unit/Framework/MockRuntimeSystem.hpp:15:0,
                 from /home/geoffrey/Codes/spectre/spectre/tests/Unit/Framework/ActionTesting.hpp:17,
                 from /home/geoffrey/Codes/spectre/spectre/tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp:26:
/home/geoffrey/Codes/spectre/spectre/tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp: In lambda function:
/home/geoffrey/Codes/spectre/spectre/tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp:306:43: internal compiler error: in is_normal_capture_proxy, at cp/lambda.c:287
                                           expected_primal_fluxes_vars,
                                           ^
/home/geoffrey/Codes/spectre/spectre/tests/Unit/Framework/TestHelpers.hpp:466:58: note: in definition of macro ‘CHECK_VARIABLES_CUSTOM_APPROX’
         std::decay_t<decltype(a)>, std::decay_t<decltype(b)>>>::apply(a, b,  \
                                                          ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/Test_DgOperator.cpp.o] Error 1
make[1]: *** [tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeFiles/Test_EllipticDG.dir/all] Error 2
make: *** [all] Error 2
~~~

### Environment:
I built this on ocean using the `ocean_gcc.sh` environment.

~~~
CMake Version: 3.18.5
SpECTRE Version: 2021.05.03
Git description: v2021.05.03-61-gcd35535df
Git branch: TimeDependentExportCoords
Git hash: cd35535df1445c0c849afcf56fc2082228fc8ed5
Hostname: ocean.fullerton.edu
Host system: Linux-3.10.0-957.1.3.el7.x86_64
Host system version: 3.10.0-957.1.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/opt/ohpc/pub/apps/charm_6.10.2_libs/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/g++
CMAKE_CXX_COMPILER_VERSION: 7.3.0
CMAKE_C_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/gcc
CMAKE_C_COMPILER_VERSION: 7.3.0
CMAKE_Fortran_COMPILER: /opt/ohpc/pub/compiler/gcc/7.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python Version: 3.7.4
~~~

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

<s>Presumably</s> fixes #3206.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@geoffrey4444 and @MarloMo could you check if this fixes #3206?

**Comment by nilsdeppe** [comment]
this fixes the issue for me on Wheeler

**Comment by MarloMo** [comment]
yes @nilsleiffischer, that fixed the problem.

**Comment by nilsvu** [comment]
maybe we should use gcc 7.3 instead of 7.5 in the container then..

**Comment by nilsdeppe** [comment]
I have no objection to using gcc 7.3 in the container, but I don't have the time to make that switch. I'm not sure if GCC 7.3 is available through apt, if it is then it should be a fairly easy adjustment

**Review by nilsdeppe — APPROVED** [review]

**Review by geoffrey4444 — CHANGES_REQUESTED** [review]
I verified that this change does let the code build on ocean with gcc 7.3.0, but these unit tests failed:

136 - Unit.DataStructures.Tensor.EagerMath.DeterminantAndInverse (Failed)
446 - Unit.Evolution.Subcell.Fd.Reconstruction (Failed)

Unit.DataStructures.Tensor.EagerMath.DeterminantAndInverse fails in a way that looser tolerances probably would fix: 

~~~
CHECK( (get<0, 2>(get<MyInvTag>(det_inv))) == DataVector({0.0, 0.0}) )
with expansion:
  (-0,4.62593e-18) == (0,0)
~~~

A similar issue affects Unit.Evolution.Subcell.Fd.Reconstruction:

~~~
CHECK( a == appx(b) )
with expansion:
  63.00000000000352429 == Approx( 63.0 )
~~~

Should we loosen those tolerances so these tests pass, or might this indicate a problem with the workaround? Note that these tests fail every time for my ocean gcc build.

**Comment by nilsdeppe** [comment]
oof I think this is GCC generating sketchy math code, but we can just relax the tolerance in those cases. We've had to do that before for other tests with GCC 7.3

**Comment by nilsvu** [comment]
@geoffrey4444 looser tolerances seem fine. Would you mind doing that so you can make sure it works on ocean?

**Comment by nilsdeppe** [comment]
@geoffrey4444 can you please fix the tolerances after this is merged? This is a critical bugfix so the code at least compiles again...

**Review by geoffrey4444 — APPROVED** [review]
Let's just merge this...and I'll submit a followup for the looser tolerances after verifying I need them after this PR is merged

**Pull request merged**
