### PR TITLE
Set SpherepackIterator by compact index

### PR DESCRIPTION
**Pull request by knelli2**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by kidder — COMMENTED** [review]
What is the use case for this?

**Comment by knelli2** [comment]
For the shape map, to determine the name of a component for writing data to disk, the only info I have is an index `i` into a SPHEREPACK array, and the total size of that array. Using #4007, I can convert `i` to a compact index (or a nullopt if it doesn't point to a valid index), which is what SpherepackIterator uses internally. However, I currently don't have a way to actually set the iterator to this compact index. That's what this PR is. Here's the block of code I plan to use it in:

```cpp
static std::optional<std::string> component_name(
      const size_t i, const size_t num_components) {
    // num_components = 2 * (l_max + 1)**2 if l_max == m_max which it is for the
    // shape map. This is why we can divide by 2 and take the sqrt without
    // worrying about odd numbers or non-perfect squares
    const size_t l_max = -1 + sqrt(num_components / 2);
    SpherepackIterator iter(l_max, l_max);
    const auto compact_index = iter.compact_index(i);
    if (compact_index.has_value()) {
      iter.set(compact_index.value());
      return {"(l,m)=("s + get_output(iter.l()) + ","s + get_output(iter.m()) +
              ")"s};
    } else {
      return std::nullopt;
    }
  }
```

**Review by kidder — DISMISSED** [review]

**Comment by kidder** [comment]
this needs a rebase

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
ignoring mac CI failure fixed in #4170

**Pull request merged**
