### PR TITLE
Move generic observe events to ParallelAlgorithms

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

These events are not evolution-specific since they only need the analytic solution. They can retrieve it from the DataBox for both the evolution and the elliptic code.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by kidder — COMMENTED** [review]
Why a separate directory `ParallelAlgorithms/Events` and not just use the moved (in #1692) `ParallelAlgorithms/EventsAndTriggers` ?

**Comment by nilsvu** [comment]
@kidder My intention was to separate the `EventsAndTriggers` _framework_ from the implementation of particular events or triggers. The latter can be general (placed in `ParallelAlgorithms`) or specific to particular components (placed in their respective directory).
These observe events, for example, are not part of the framework but only make use of it. We could place them in `PA/EventsAndTriggers/Events` I suppose, but I felt like the nesting was unnecessary. Happy to hear alternative ideas though!

**Review by wthrowe — APPROVED** [review]
I like @nilsleiffischer's directory structure.

**Review by kidder — APPROVED** [review]
Okay sounds reasonable

**Comment by nilsvu** [comment]
Travis passed, looks like this is ready to go

**Pull request merged**
