### PR TITLE
Require LIBXSMM 1.16.1

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

There's a bug fix somewhere between 1.9 and 1.16.1 that fixes single-row matrix
multiplication. Since LIBXSMM is easy to install manually, this bumps to most
recent rather than spending time figuring out which release fixes the bug.

### Upgrade instructions

Upgrade your local LIBXSMM installation to 1.16.1 or newer, or update to the latest container

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Review by fmahebert — CHANGES_REQUESTED** [review]
Add version requirement for installation dox?

**Comment by nilsdeppe** [comment]
:( I actually thought about that and then forgot... Done now :)

**Review by fmahebert — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Review by nilsvu — APPROVED** [review]
Shall we wait a few days before merging this to give people a chance to upgrade their environments? Given your announcement on Slack I think merging this tomorrow would be fine.

**Comment by nilsdeppe** [comment]
Yep, would also be in line with our "wait 48 hours from when the PR is opened to merge". It's not a critical bug that's breaking develop :)

**Pull request merged**
