### PR TITLE
Update python on ocean

### PR DESCRIPTION
**Pull request by geoffrey4444**
## Proposed changes

Update python on ocean to version 3.9.5, a new module on ocean that doesn't use anaconda, as previous python modules on ocean did.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsvu — APPROVED** [review]
Haven't checked this actually works on Ocean

**Comment by kidder** [comment]
@nilsleiffischer the failed test here is from /__w/spectre/spectre/tests/Unit/Elliptic/Systems/Xcts/Test_Equations.cpp:153
Also how can `codecov/project` fail on something that doesn't touch code?  It appears to be failing in all of the PRs...

**Comment by nilsvu** [comment]
@kidder Addressed those two things in #3404 and #3403.

**Comment by geoffrey4444** [comment]
@kidder @nilsleiffischer thanks for taking a look at this PR! I would like to move my group over to using my new python installation...is there anything you're waiting on from me for this PR to move forward?

**Comment by kidder** [comment]
just approval from someone who has access to ocean

**Comment by geoffrey4444** [comment]
I'm happy to make an account for anyone willing to review! Please just ping me on slack

**Comment by kidder** [comment]
@MarloMo can you checkout this branch, and compile spectre on ocean and confirm that you can build

**Comment by MarloMo** [comment]
Built and tests passed on Ocean for me. @kidder @geoffrey4444

**Pull request merged**
