### PR TITLE
Work around H5 issue with signed chars

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

See issue https://github.com/sxs-collaboration/spectre/issues/5029

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
This workaround doesn't actually break anything, but should allow the deserialization tests in the ARM container to pass.

**Review by wthrowe — APPROVED** [review]
We should figure out how to do this properly, but if this works around the current problem that's lower priority.

**Review by geoffrey4444 — APPROVED** [review]
I verified that this lets the python tests pass both in an arm64 docker container and in a native build on my Mac. I do notice a CI failure (timeout in Unit.Evolution.Systems.CurvedScalarWave.Worldtube.Tags) that appears unrelated to this PR.

**Review by knelli2 — APPROVED** [review]

**Comment by kidder** [comment]
ignoring test time out

**Pull request merged**
