### PR TITLE
Add resubmit capability to Wheeler submit script

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

This is very similar to the `OceanClang.sh` submit script.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — CHANGES_REQUESTED** [review]
Quoting @kidder in #3792:
> If we are going to standardize submit scripts, there needs to be a group discussion among core developers and other interested parties before proceeding with this...

See also my (rather empty) issue #2987.

My own interpretation of all that is that we don't have consensus that what Ocean (or any other machine) does is desirable, so modifying the behavior of other machines to match is frowned upon until some thought has been put into that question.  I encourage you to start that discussion, although if you want to have it here or on the above issue make sure to advertise it since most potentially interested parties don't read comments on random PRs.

**Comment by knelli2** [comment]
@wthrowe Sorry, this was discussed at the meeting today (1/23/23) and the consensus was that we don't know what all the submit scripts should look like in general, but since Wheeler is used by a lot of us and we want this capability on Wheeler specifically, to just change it for Wheeler and not other machines.

**Review by wthrowe — APPROVED** [review]
OK.  (This would have been a good thing to include in the meeting minutes.)

I will object to any future changes along these lines, however.

**Comment by knelli2** [comment]
@wthrowe Sorry I forgot to add that to the minutes. I made an edit at the end for future reference (https://github.com/sxs-collaboration/spectre-call-notes/issues/179)

**Review by nilsdeppe — APPROVED** [review]
I agree with @wthrowe, we shouldn't keep doing these hacks. I've added my thoughts on that issue.

**Pull request merged**
