### PR TITLE
Add iter_elements Python function

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Iterate over elements and their tensor data in H5 volume files.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@wthrowe does this address your #3414?

**Comment by wthrowe** [comment]
Yes, I think this covers the main points.

**Comment by nilsvu** [comment]
@wthrowe would you be willing to review this?

**Comment by wthrowe** [comment]
No.  I'm not qualified.

**Review by nikwit — APPROVED** [review]
LGTM

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
