### PR TITLE
Switch to C++17

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

- Enable C++17. Had to do a couple minor code changes to get it working. One is a bug in pybind11, while the type traits change is needed because as of C++17 `noexcept` is part of the function signature.
- Replace all `cpp17::*` code with `std::*` code except `cpp17::array` and `cpp17::void_type` since those might not be trivial find-replace

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by fmahebert** [comment]
Should this PR also remove our `cpp17::blah` implementations?

**Comment by nilsdeppe** [comment]
That could end up being a lot of work that I don't have time to put in right now... I expect most of the removals will be trivial, but I wouldn't be surprised if we got some things wrong

**Comment by wthrowe** [comment]
The C++17 changes look fine.

**Comment by fmahebert** [comment]
@nilsdeppe Understandable — what do you think about opening an issue to remind us that we should remove `cpp17` when we can?

**Comment by nilsdeppe** [comment]
Dropped the first two commits to make this no longer dependent on finding the pybind11 version (we can support all versions fine just by specifying `-fsized-dellacation` when building bindings with clang).

I've done the trivial find-replaces of `cpp17` -> `std`. The remaining one will probably actually take some work.

Marked `in progress` until CI is done and everything seems to be working. I'll ping folks then.

**Comment by nilsdeppe** [comment]
@fmahebert created #2194

**Comment by wthrowe** [comment]
I am fine with this assuming CI is happy.

**Comment by nilsdeppe** [comment]
@wthrowe I've squashed the fixup in and also a missed `cpp17::negation` in `Test_SelfStartActions`.

Interestingly, with this GCC takes 50% longer to build the executables, while clang builds are basically unchanged. It's not clear why this is and how much our variance between builds is in general. Given @kidder is working on reducing the build time by simplifying the `DataBox` I'm not sure how much we should worry about the time increase.

**Review by wthrowe — APPROVED** [review]
That's weird, but I guess I'm OK with the time increase.  Anyone developing with gcc must already be pretty sad, and the compilation time for production doesn't matter that much.

**Review by kidder — APPROVED** [review]

**Pull request merged**
