### PR TITLE
Remove IWYU

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

This never really worked that well for us and we've had it disabled for a while now. I don't think we'll be trying to revive it again so I'm just removing it.

### Upgrade instructions

Removed include-what-you-use (IWYU) as a dependency.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]
:tada: Thanks for doing this :D

**Comment by knelli2** [comment]
Umm GCC is unhappy and I'm not really sure why...

Edit: Oh I think it's the PCH.

**Comment by wthrowe** [comment]
I agree, it looks like the PCH didn't rebuild properly for some reason, but I don't see an obvious cause.

Otherwise, this looks good.

**Comment by knelli2** [comment]
Let's see if a rebase fixes things.

Edit: Sad...it did not...

**Comment by wthrowe** [comment]
My guess is you've hit some inconsistency in how ccache and gcc (for pragma once) decide that a header is unchanged.  Try making some change to `TMPL.hpp` that isn't just comments or add a blank line or something to change line numbers.

**Review by wthrowe — DISMISSED** [review]
Looks like it's compiling now.

**Comment by knelli2** [comment]
@wthrowe @nilsdeppe clang-tidy timed out because there were too many changed files, however, I noticed we were only running it on 1 core, so I added a commit to run it on 4 cores and we'll see if that helps. Otherwise just a rebase.

Edit: Looks like clang tidy still failed. This time I think `-j4` caused it to run out of memory with so many files.

**Review by nilsdeppe — DISMISSED** [review]

**Review by wthrowe — CHANGES_REQUESTED** [review]
Let's drop the commit that crashed clang-tidy.  I'm not worried about the timeout on a PR like this.

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
