### PR TITLE
Update docker github actions

### PR DESCRIPTION
**Pull request by kidder**
## Proposed changes

The actions for building a docker container need to be updated

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsvu — APPROVED** [review]
What was the problem? And have you tested the new version?

**Comment by kidder** [comment]
It failed to deploy a container, with the following errors:
```
[Build and deploy](https://github.com/kidder/spectre/actions/runs/9271381958/job/25506598463#step:6:13169)
buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get update -y     && apt-get install -y python3-pip python-is-python3     && pip3 --no-cache-dir install pybind11~=2.6.1     && pip3 --no-cache-dir install -r requirements.txt -r dev_requirements.txt     && rm requirements.txt dev_requirements.txt" did not complete successfully: exit code: 1

Build and deploy
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/setup-qemu-action@v2, docker/setup-buildx-action@v2, docker/login-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```


After updating, the actions, I am able to deploy a container

**Comment by nilsvu** [comment]
Ok great! What was the error in the pip install? I think I tried recently and it wanted to build wheels for h5py for some reason and failed, was that the error here too?

**Comment by kidder** [comment]
The only error message I could see was the one above...  After I updated the actions I didn't get an error

**Pull request merged**
