### PR TITLE
Subcell: Prep GRMHD, var fixers return bool, add subcell dir to GRMHD, return status in recovery

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

- Adds `ValenciadivClean/Subcell` directory. This is where things like the system-specific TCI will live.
- Make the GRMHD variable fixer return whether or not it fixed the conservative variables. We will use having to fix the conserved variables as a method of preventing returning to DG when we are on subcells. That is, if the FD solution needed fixing, there's no way the DG solution will work.
- Add ability for prim recovery schemes to return whether or not the recovered the vars. This is needed because with DG-subcell we will use failed prim recovery while on DG as a TCI and switch to subcell then.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
Note: The clang-tidy failure is in Boost, nothing I can do about it :(

**Review by kidder — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
I rebased on develop to deal with conflicts from moving the thermodynamic dim to the `apply` function in prim recovery.

**Review by kidder — DISMISSED** [review]

**Review by fmahebert — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
I rebased this to resolve a conflict in the `CMakeLists.txt` for `add_subdir(FiniteDifference)` and `add_subdir(Subcell)`. Thanks for the reviews :)

**Review by kidder — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]

**Comment by nilsdeppe** [comment]
clang-tidy failure is inside Boost

**Pull request merged**
