### PR TITLE
Move time-dependent maps into sub dir and namespace

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

- Move time-dependent maps into `CoordinateMaps/TimeDependent` and into the namespace `CoordinateMaps::TimeDependent`

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Review by fmahebert — DISMISSED** [review]
For my understanding: is ProductMap moved into TimeDependent because in general it could be composing maps that are time dependent? I didn't think there was inherent time dependence there.

**Comment by nilsdeppe** [comment]
@fmahebert we have both time-dependent and time-independent product maps. I moved the time-dependent ones :)

**Comment by kidder** [comment]
@nilsdeppe can you double check if this needs rebasing after #2109 was merged

**Comment by nilsdeppe** [comment]
@kidder updated :)

**Review by kidder — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]

**Pull request merged**
