### PR TITLE
Check if Charm++ is SMP and add macro if it is

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

For storing large datasets like tabulated equations of state we will likely want
to know if Charm++ was built in SMP mode so we know whether we can afford to
store the table in memory.

This came up on the Charm++ mailing list and I figured it would be useful for us to have.

### Types of changes:

- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
Why don't we just use the CMK_SMP macro?

**Comment by nilsdeppe** [comment]
because I don't find that name to be very enlightening so if I were reading the code I'd have to figure out what the `ifdef` is doing somehow. I'm also not sure which header files Charm++ guarantees `CMK_SMP` will be defined in if included

**Comment by wthrowe** [comment]
But we could just define our macro in terms of that, rather than parsing C++ code with regular expressions.  Something like a `SpectreSharedMemoryParallelismBuld.hpp`:
```c++
#include <conv-mach.h>
#ifdef CMK_SMP
#define SPECTRE_SHARED_MEMORY_PARALLELISM_BUILD 1
#endif /* CMK_SMP */
```

**Comment by nilsdeppe** [comment]
I'd also like the Charm++ build type to be reported in the CMake (which has reminded me that it should be written into the version/env info file CMake writes out)

**Comment by wthrowe** [comment]
OK, that's reasonable.

Are there known cases where conv-mach.h should not exist?  If not, I think we should error in that case rather than guess the answer and potentially switch to the slow paths unnecessarily.

**Comment by nilsdeppe** [comment]
The Charm++ developers recommend checking `conv-mach.h` for whether or not SMP is enabled, so there should never be a case where it's not present. I've just added the error if the file doesn't exist.

**Review by kidder — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
