### PR TITLE
Merge 'combine-h5 {dat,vol}' CLI commands

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

<s>Preparation for #5410.</s>

Make the dat and vol commands subcommands of 'combine-h5'.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@geoffrey4444 your function to combine dat files can be added here.

**Review by knelli2 — COMMENTED** [review]
Looks good except for tests

**Review by knelli2 — DISMISSED** [review]

**Comment by knelli2** [comment]
Maybe do #5410 as well, now that it's merged?

**Review by knelli2 — APPROVED** [review]
Looks good!

**Comment by knelli2** [comment]
Ignoring CI timout

**Pull request merged**
