### PR TITLE
Print backtrace in FixedHashMap exceptions, abbreviate function name in ERROR

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Print backtrace in out-of-range errors that occur in commonly used containers, like `DirectionMap`.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@wthrowe I remember discussion about `ERROR(..., exception_type)`. Were you going to add that? Would be useful here.

**Comment by wthrowe** [comment]
I think @nilsdeppe was looking into that.

**Comment by nilsdeppe** [comment]
Yes, but I haven't written any actual code for it. My plan is to template `abort_with_error_message` on the exception type to throw, and then do explicit instantiations for all the std and our own exception types.

**Comment by nilsvu** [comment]
Included in #5467

**Pull request closed without merging**
