### PR TITLE
Use FixedHashMap instead of unordered_map in Domain, Block

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Implements the last bit of #745 using `FixedHashMap`

closes #745

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by kidder** [comment]
How about a type alias
```
template <size_t VolumeDim, typename T>
using DirectionMap = FixedHashMap<2*VolumeDim, Direction<VolumeDim>, T, DirectionHash<VolumeDim>;
```
or even better, it looks like the third argument is always `T<VolumeDim>`

**Comment by nilsdeppe** [comment]
How about a strong typedef so we could forward declare it?

**Comment by nilsdeppe** [comment]
@kidder should be done :)

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
@wthrowe please look at

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
