### PR TITLE
Remove DG boundary schemes code

### PR DESCRIPTION
**Pull request by nilsvu**
We intended to share this DG logic between evolution and elliptic
executables, but it turned out to be easier to implement the schemes
separately. Evolution and elliptic code still share the low-level DG
logic in NumericalAlgorithms/ but implement their own parallel
algorithms and DataBox-handling code.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]
This might be the easiest review possible... If it builds it's good to go, right? :P

**Comment by nilsvu** [comment]
I suppose so, though we should make sure not to delete code that might still be useful, e.g. hasn't been migrated yet (some numerical fluxes, some tests).

**Comment by nilsdeppe** [comment]
Agreed. None of the evolution can be using the deleted files because that code was removed from `ComputeTimeDerivative` so as far as the evolution code is concerned, everything here is safe to delete :)

**Comment by nilsvu** [comment]
@kidder or @wthrowe could you take a look at this one?

**Comment by kidder** [comment]
This LGTM.  Can you rebase and make sure it still works.  I worry about the generalized harmonic executables and the new GR+MHD executables

**Review by nilsdeppe — APPROVED** [review]
@kidder can you look at again?

**Review by kidder — APPROVED** [review]

**Pull request merged**
