### PR TITLE
Add macro to approximately compare containers

### PR DESCRIPTION
**Pull request by wthrowe**

### CODE REVIEW

**Review by kidder — COMMENTED** [review]
I think this should include a CHECK that both containers are not empty as I see no reason you would call this on empty containers

**Comment by wthrowe** [comment]
I'm a bit worried about the empty container check since we already compare empty containers for strict equality in our tests, but we can remove it when we hit it.

**Comment by kidder** [comment]
My suggestion would be that in the test if we know both containers are empty, we should just check that they are empty instead of comparing them.

**Comment by wthrowe** [comment]
The code doing the test doesn't necessarily know that (although it could check, I suppose).  I'm thinking of generic code that is just passed an expected value like our [checks that blocks have the correct neighbors](https://github.com/sxs-collaboration/spectre/blob/develop/tests/Unit/Domain/TestDomainHelpers.hpp#L34).

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
I agree with both of your arguments. We probably want to get some usage experience and then decide. We could always have another macro that allows zero sized containers to compare equal.

**Review by kidder — DISMISSED** [review]
Please squash

**Comment by wthrowe** [comment]
Please hold off on merging this while I figure out how to resolve some issues changes here caused in #313.

**Comment by wthrowe** [comment]
I have a fix for #313.  No changes are required to this pull request.

**Review by kidder — APPROVED** [review]

**Pull request merged**
