### PR TITLE
Change unit test default timeout to 5 seconds

### PR DESCRIPTION
**Pull request by kidder**

### CODE REVIEW

**Comment by nilsdeppe** [comment]
If this works we can have CMake check an env variable to see if things are running on Travis. We probably also want to have the limit as minimal as possible, and maybe ctest or something else can even print out ones that take longer. Thoughts?

**Comment by nilsdeppe** [comment]
So the longest was 2.81 seconds. I wonder if 4 seconds would be enough. @fmahebert would you mind testing that on your machine? I think as a general rule shorter tests are still better and they should finish locally in under 2 seconds in general. The other reason for this is that running tests on KNL takes about 2x longer because the processors are 2x slower.

**Review by osheamonn — APPROVED** [review]

**Comment by nilsdeppe** [comment]
I object to this change without explicit statement in the dev guide somewhere that the goal should still be under 2 seconds.

**Comment by kidder** [comment]
Okay, I will update the dev guide

**Comment by fmahebert** [comment]
This commit was merged before I had a chance to test on my desktop... so here's a belated report.

I am no longer able to reproduce the tests timing out, with or without this commit. I suspect this could be due to a Linux kernel/system update I made since looking into the timeouts with @nilsdeppe a week ago, but have not been able to confirm this.

**Pull request merged**
