### PR TITLE
Simplify elliptic DG formulation

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Remove the notion of "auxiliary variables". Just always choose the partial derivatives of the system variables as auxiliary variables. This doesn't change Poisson and Puncture systems at all, but Elasticity and XCTS systems change at truncation error level.

This simplification helps to reformulate the DG scheme in a next PR. It also makes it easier to implement elliptic systems altogether and improves performance by ~20% because it eliminates Kronecker-deltas in the formulation.

### Upgrade instructions

In elliptic systems remove the `auxiliary_fields` and `auxiliary_fluxes`. Instead, formulate your fluxes in terms of the partial derivatives of the systems fields. See the `FirstOrderSystem` protocol for details.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
@nilsdeppe would you be willing to review this? It's the first step in the elliptic DG journey to fix the large outer boundaries.

**Comment by nilsdeppe** [comment]
Yes! I've got a couple bigger PRs from Will to review, but I think by Tuesday I'll be able to get to this at the latest :)

**Review by nilsdeppe — COMMENTED** [review]
LGTM but needs a rebase to resolve conflicts

**Comment by nilsvu** [comment]
Rebased, thanks for reviewing!

**Comment by nilsdeppe** [comment]
RIP CI :(

**Comment by nilsvu** [comment]
Fixed!

**Review by nilsdeppe — APPROVED** [review]
🎉

**Pull request merged**
