### PR TITLE
Lint "mutable" keyword and clean up "noexcept" test

### PR DESCRIPTION
**Pull request by wthrowe**
This implementation reuses the NOLINT and NOLINTNEXTLINE magic comments.  It's easy to change to another method of whitelisting if people don't like that overloading.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — APPROVED** [review]
This is great! Thanks so much for doing this!

I can't comment on any of the elliptic mutables. Here are my thoughts:
- `DataBox` this is worrisome, but we'll need to look at where we have locks in the node groups. I think only in node groups can this be an issue.
- CCE: probably all of these are bad. I'm not sure where the analytic solutions are stored for CCE, but this just looks like the sort of thing that will cause trouble at some point.
- H5/File: I'll look into this one. I'm worried about it, but not super worried since we already need to use locks to access files. At the very least there needs to be a Doxygen warning and some comment explaining it.
- NumericalAlgorithms/*: probably everything here should be thread safe. These are serial algorithms and so there's no real reason to have them not be threadsafe.
- Parallel Schwarz: I'm not qualified to answer.
- Tests: if used in a test executable, probably suspect....

I can make an issue next week listing all these and pinging the appropriate expert on each :)

**Comment by nilsvu** [comment]
Nice solution! Suggestion: shall we require (in code review) to add a brief reasoning and a statement on thread safety to the docs of a class when it uses mutable members? Something like: "this class uses mutable member variables as buffers and is not thread safe. Only use in a single thread, e.g., in the DataBox of an element or a singleton, but not in the GlobalCache." (The DataBox statement is a bit vague, but I can't think of a better wording right now. It's supposed to give new users an idea which contexts might be dangerous and which are probably fine.)

**Comment by wthrowe** [comment]
I like the idea of noting in documentation that the classes aren't thread-safe (although I'd add protecting with a lock to the list of acceptable uses).  Maybe even add some sort of justification, although in most cases I expect it would just that we only expect to use it in serial code so maybe only if that isn't the reason (such as for DataBox, where non-serial access protected by a lock is expected).

The tricky part is that any class with a non-thread-safe member variable is also potentially non-thread-safe, and that's harder to catch.

As for specific cases:

* I think CCE is entirely serial, so the analytic solution ones are probably OK unless they are being used to feed Cauchy boundary conditions for CCM testing or something.  The WorldtubeDataManager classes have some lock-related code, so they've already been thought about.
* Presumably HDF5 file access isn't thread safe (At least writing? Maybe reading is.), so I'm not too worried about adding more non-thread-safe stuff in the wrappers.
* I agree it would be good if everything in NumericalAlgorithms was safe.
* I think test stuff is OK in RunTests (always serial), but maybe not in some of the specialized executables.
* The one in Time is OK because what are you doing doing LTS boundary communication on a NodeGroup?
* The MathWrapper one is OK because it is supposed to have pointer/reference semantics, and you probably shouldn't be storing them long-term anyway, but it might be worth noting that in the docs.

**Comment by nilsvu** [comment]
@kidder do you want to review this as well?

**Comment by kidder** [comment]
This LGTM.  Should we create an issue (or issues) so the above list of mutable variables are either made non-mutable or have their thread-safety documented.

**Review by kidder — APPROVED** [review]
@wthrowe merge this if you are happy with it

**Comment by nilsdeppe** [comment]
I've filed an issue https://github.com/sxs-collaboration/spectre/issues/3936 hopefully correctly documented what was discussed here. Please comment on the issue if I've misrepresented anything!

**Pull request merged**
