### PR TITLE
Change non-monotonic AM predictor coefficients

### PR DESCRIPTION
**Pull request by wthrowe**
Either version works, but this version makes the analytic expressions nicer and is what will be in the paper.

Note that this does not affect the BBH paper, because that uses the monotonic method.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
@wthrowe I don't know if this relates at all to your group meeting update, but in any case, I'll let you merge it when you are ready :)

**Comment by wthrowe** [comment]
That's a good question, actually.  Maybe I should hold off on this until I figure out exactly what we want.

**Comment by knelli2** [comment]
@nilsdeppe @wthrowe Maybe post a quick synopsis of what was brought up so we have a record of it?

**Comment by wthrowe** [comment]
Basically, what's on develop, what's in this PR, and what I wrote in my paper draft are all different.  They all satisfy the requirements on the method, so it's not clear which one to choose.  (And I'm now also considering a fourth version.)

**Comment by wthrowe** [comment]
Decided to go with a simpler version without the conditional on alignment.  This should be ready now.

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
