### PR TITLE
Fix rebase issue from #5877

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

This was my bad. Merged #5877 too quickly.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — CHANGES_REQUESTED** [review]
The include is unused and misformatted.  Just delete it.

**Comment by knelli2** [comment]
The commented code won't compile without it if somebody tries it. Should we just keep it, but with the proper formatting?

**Comment by wthrowe** [comment]
There shouldn't be a giant block of commented code either, but I wasn't going to ask you to fix that in this PR.

**Comment by knelli2** [comment]
@wthrowe Ok I just removed it

**Review by wthrowe — APPROVED** [review]

**Comment by wthrowe** [comment]
Filed #5926 for the commented code.

**Pull request merged**
