### PR TITLE
Fix 1843: raise tolerance

### LINKED ISSUE #1843: Random failure in Unit.Evolution.Systems.GeneralizedHarmonic.Gauge.DampedHarmonic.details
# Bug reports:

```
2019-12-08T23:00:27.5961473Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-08T23:00:27.5961761Z "Debug.Unit.Evolution.Systems.GeneralizedHarmonic.Gauge.DampedHarmonic.details" is a Catch v2.2.1 host application.
2019-12-08T23:00:27.5962246Z Run with -? for options
2019-12-08T23:00:27.5962524Z 
2019-12-08T23:00:27.5963010Z -------------------------------------------------------------------------------
2019-12-08T23:00:27.5963336Z Unit.Evolution.Systems.GeneralizedHarmonic.Gauge.DampedHarmonic.details
2019-12-08T23:00:27.5963843Z -------------------------------------------------------------------------------
2019-12-08T23:00:27.5964833Z /__w/spectre/spectre/tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_DampedHarmonicGaugeQuantities.cpp:2976
2019-12-08T23:00:27.5965104Z ...............................................................................
2019-12-08T23:00:27.5965274Z 
2019-12-08T23:00:27.5965461Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2019-12-08T23:00:27.5965630Z   CHECK( a == appx(b) )
2019-12-08T23:00:27.5965811Z with expansion:
2019-12-08T23:00:27.5966905Z   -0.5275990716 == Approx( -0.5275990716 )
2019-12-08T23:00:27.5967183Z with messages:
2019-12-08T23:00:27.5967615Z   Seed is: 2304299897 from /__w/spectre/spectre/tests/Unit/Pypp/
2019-12-08T23:00:27.5967907Z   CheckWithRandomValues.hpp:356
2019-12-08T23:00:27.5968129Z   function: spacetime_deriv_log_fac
2019-12-08T23:00:27.5968363Z   /__w/spectre/spectre/tests/Unit/Pypp/CheckWithRandomValues.hpp:224: result ==
2019-12-08T23:00:27.5968805Z   pypp::call<ResultType>( module_name, function_name, std::get<ArgumentIs>
2019-12-08T23:00:27.5969115Z   (args)..., forward_to_pypp<ResultType>(std::get<MemberArgsIs>(member_args),
2019-12-08T23:00:27.5969338Z   used_for_size)...)
2019-12-08T23:00:27.5969969Z   a: T(0)=-5.275990715902025840e-01
2019-12-08T23:00:27.5970214Z   T(1)=2.002487066594059115e+03
2019-12-08T23:00:27.5970410Z   T(2)=1.205127710899508884e+03
2019-12-08T23:00:27.5970822Z   b: T(0)=-5.275990715929310682e-01
2019-12-08T23:00:27.5971055Z   T(1)=2.002487066594059115e+03
2019-12-08T23:00:27.5971250Z   T(2)=1.205127710899508884e+03
2019-12-08T23:00:27.5971859Z   a: -5.275990715902025840e-01
2019-12-08T23:00:27.5972277Z   b: -5.275990715929310682e-01
2019-12-08T23:00:27.5972482Z 
```

### PR DESCRIPTION
**Pull request by geoffrey4444**
## Proposed changes

Fixes #1843 ... reproduced failing seed, with looser tolerances, test passed 1000 times.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [x] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
Did someone restart the checks? I've been trying to comment why I restarted them (what the error was) so that other reviewers and people can have some idea of what is happening :)

**Review by moxcodes — DISMISSED** [review]

**Comment by geoffrey4444** [comment]
> Did someone restart the checks? I've been trying to comment why I restarted them (what the error was) so that other reviewers and people can have some idea of what is happening :)

I restarted the checks, but they failed a second time. Maybe I restarted them too soon?

**Comment by nilsdeppe** [comment]
@geoffrey4444 okay, could you please look at why they failed and add that as a comment when restarting? That helps us diagnose recurring issues :) 

This time they failed because of a timeout with `Unit.NumericalAlgorithms.Interpolator.ApparentHorizonFinder`. This should be fixed on develop with #2171 so I think you should just need to rebase on develop.

**Comment by geoffrey4444** [comment]
> @geoffrey4444 okay, could you please look at why they failed and add that as a comment when restarting? That helps us diagnose recurring issues :)
> 
> This time they failed because of a timeout with `Unit.NumericalAlgorithms.Interpolator.ApparentHorizonFinder`. This should be fixed on develop with #2171 so I think you should just need to rebase on develop.

Yep! I'll do that from now on, and I'll rebase this one.

**Review by nilsdeppe — APPROVED** [review]
Okay, thanks @geoffrey4444!

**Review by kidder — APPROVED** [review]

**Review by moxcodes — APPROVED** [review]

**Comment by geoffrey4444** [comment]
Checks still failed, this time because of random test failure (suspect roundoff) in ValenciaDivClean, e.g.

I'll try restarting to see if it happens again.

~~~
1270
  CHECK( a == appx(b) )
1271
with expansion:
1272
  -0.8878964608 == Approx( -0.8878964608 )
1273
with messages:
1274
  Seed is: 3751472509 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
1275
  GrMhd/ValenciaDivClean/Test_Characteristics.cpp:50
1276
  /__w/spectre/spectre/tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/
1277
  Test_Characteristics.cpp:105: grmhd::ValenciaDivClean::characteristic_speeds(
1278
  rest_mass_density, specific_internal_energy, specific_enthalpy,
1279
  spatial_velocity, lorentz_factor, magnetic_field, lapse, shift,
1280
  spatial_metric, normal, eos_base) == (pypp::call<std::array<DataVector, 9>>(
1281
  "TestFunctions", "characteristic_speeds", lapse, shift, spatial_velocity,
1282
  spatial_velocity_squared, sound_speed_squared, alfven_speed_squared, normal))
~~~

**Pull request merged**
