### PR TITLE
Add ObserveAtPoint event

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Interpolate tensors to a user-specified point. This is an easy way to
compare simulation data on different grids, or from different codes
(e.g. compare to SpEC).

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by kidder** [comment]
This functionality already exists in more generic form with interpolation targets so why duplicate it?

**Comment by nilsvu** [comment]
@kidder That's how I started with this, modifying `intrp::Events::InterpolateWithoutInterpComponent`, but then I realized there's this whole tail of complexity that comes with it: To adopt this simple feature all executables need to define `interpolator_source_vars`, `interpolation_target_tags`, add the `intrp::Actions::ElementInitInterpPoints` action, add the `intrp::InterpolationTarget` parallel component, and define the interpolation target with things like `tags_to_observe`, `vars_to_interpolate_to_target`, `post_interpolation_callback`, `compute_target_points` and so on, including logic to control which tensors to interpolate and handling compute items. This seems like way too much overhead.

On the other hand, in the `ObserveAtPoint` event all I need is construct an `intrp::IrregularInterpolant` and send the data to the observer like the other observation events do. This way, the feature is available in all executables just as a normal event, no need to change anything in the executables at all, and it works with ObservationBox etc. The complexity from the parallel interpolation framework may be necessary for things like apparent horizons, but I think it's overkill for this.

**Comment by nilsvu** [comment]
This has been rebased. As discussed a few weeks ago, the plan is to generalize this to support more interpolation targets in follow-up work.

**Comment by nilsvu** [comment]
@nilsdeppe and @kidder could you look at this one please?

**Comment by nilsvu** [comment]
@kidder @nilsdeppe please take a look

**Comment by knelli2** [comment]
Can be done in post-processing or using the `SpecifiedPoints`, but would be nice to not have the overhead of the interpolation framework.

**Pull request closed without merging**
