### PR TITLE
Remove Travis build of IWYU

### PR DESCRIPTION
**Pull request by kidder**
We have experimented with IWYU for over a year, and it gives more incorrect
suggestions that require pragmas than correct suggestions.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

**Comment by fmahebert** [comment]
This PR description is very brief and does not provide the kind of big-picture information that other developers of the code may want to know, such as:

- do we want to keep any amount of IWYU-compliance in the codebase?
- do we still expect developers to run IWYU?
- do we still expect developers to be _able_ to run IWYU? (i.e., do we support using IWYU with SpECTRE?)

If the answer to these questions is no, then I argue this PR is insufficient: we need to remove the directions to run IWYU from the PR templates and various locations in the dev guide. We should remove IWYU targets from the build system. Also, we should remove the IWYU pragmas that are all over the codebase. And probably more tasks I'm not thinking of just now... If these tasks are not done in this PR there should at least be issues for them.

If the answer to these questions is yes, then I argue we need to keep running IWYU in Travis, or else IWYU issues will rapidly crop up throughout the codebase... making "support" for IWYU questionable.

**Comment by nilsdeppe** [comment]
My opinion is we should expect devs to get includes correct. Be that using IWYU or thinking about their own code (the latter is difficult to enforce other than thinking during code review).

**Review by geoffrey4444 — DISMISSED** [review]
I'm happy with removing Travis, but maybe we can see how it goes? Maybe code review is enough to catch enough #include problems that we will still avoid the big problems, like new code not compiling for unclear reasons that turn out to be someone not having correct includes.

**Comment by fmahebert** [comment]
Experience with SpEC, and more recently with SimulationAnnex and CCEAnnex, has shown us that we don't succeed at following "people should X".

Once this PR is merged, developers _might_ check the correctness of their includes, whether with IWYU or by thinking. Reviewers _might_ check for correctness of includes. But more likely, within a few weeks, we will start to have non-IWYU compliant code merged into the repository. When this occurs it will progressively become more difficult for other developers to use IWYU on their own changes. Eventually it will no longer make sense to (a) instruct developers to use IWYU, (b) provide build targets for IWYU, or (c) have IWYU pragmas all over the codebase when we don't comply with IWYU anyway.

I believe that if we aren't enforcing checks with automated tools (however flawed these tools may be (I don't dispute that IWYU is flawed)), then we may as well save time and do nothing at all. This is why I propose two opinionated options in my previous comment: I do not see how the middle-ground approach taken by this PR is an effective long term solution.

However, correctness of includes should not impact the correctness of our science. So this hill is not the hill I choose to die on.

**Comment by markscheel** [comment]
I agree with @fmahebert.  I think that if we turn off IWYU, we need to be ok with includes being completely chaotic and inconsistent (modulo what is checked by compliers and clang-tidy). Humans are not going to get includes right (humans can't even archive SpEC runs, which is way easier).  And it is a huge burden on code reviewers to check if someone else's includes are right.  As much as I complain about IWYU (and I do complain a lot), I would prefer to keep it.

**Comment by fmahebert** [comment]
(A side note: the IWYU in our container is a few versions out of date. It is possible that a more recent version may perform slightly more reliably?)

**Comment by geoffrey4444** [comment]
I agree with @fmahebert that include correctness doesn’t impact our science. So I think all that matters is which costs the humans the most time: include incorrectness or iwyu incorrectness?

**Comment by nilsdeppe** [comment]
My experience has been that IWYU is incorrect somewhere between 30-40%  of the time. The original motivation for having it was to motivate people to think about what they're including. Sadly this has not worked and there are files in the code with incorrect includes and forward declarations. The IWYU version we use is so bad that in my opinion the only way it makes sense to keep it is still to force reviewers to look at the includes simply because the tool cannot be trusted. At that point we might as well not use it so that people aren't given some false sense of security.

Some of the features listed in the newer IWYU releases are encouraging since they discuss issues we've seen, such as explicit template instantiations not counting as a "use". If someone is interested in testing it I think they should, but my observation has been that the current IWYU is doing more harm than good.

**Comment by kidder** [comment]
@fmahebert @markscheel I have updated this to remove IWYU from the PR template and added a discussion of IWYU in the documentation section for performing checks locally.

**Review by fmahebert — APPROVED** [review]

**Review by markscheel — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
Reviewed in person with @wthrowe

**Pull request merged**
