### PR TITLE
Cleanup hydro tag frames

### PR DESCRIPTION
**Pull request by fmahebert**
## Proposed changes

For our hydro/grmhd/NewtonianEuler tags that have a default frame, remove re-specification of this default frame from uses of the tag.

This change is a continuation of PR #2044, and was discussed several weeks ago with @kidder and @carmaza (no guarantees that I've implemented what @kidder actually had in mind 😛). In particular, 2044 removed default frames from some tensors too, whereas here I do not.

In other words... given a `Tags::Velocity<blah, Frame = Inertial>`, this PR changes uses of the tag from `Tags::Velocity<blah, Inertial>` to `Tags::Velocity<blah>`, but does not change uses of the corresponding `tnsr::I<blah, Inertial>`.

If we want to also remove defaults from the tensors, I can add commits that do that as well.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by carmaza — DISMISSED** [review]
This is what I remember we wanted.

**Review by kidder — DISMISSED** [review]

**Comment by kidder** [comment]
there are legitimate clang-tidy errors here

**Comment by fmahebert** [comment]
Some of these clang-tidy issues are fixed in my other open PRs (#2331 & #2332), so my plan is to wait until those are merged, then rebase and update this PR to fix any remaining clang-tidy problems.

**Comment by fmahebert** [comment]
I've rebased and added two commits with clang-tidy fixes

**Comment by fmahebert** [comment]
CI failed with a timeout

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
