### PR TITLE
Improve floating-point behavior in wedge map

### PR DESCRIPTION
**Pull request by wthrowe**
Might help with elliptic problems with very large outer radii.

@nilsvu See if this helps.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsvu — APPROVED** [review]
Thanks for doing this @wthrowe! At the very least it eliminates a factor of uncertainty in this whole large-outer-boundary issue 👍 I confirmed that the test you added fails on current develop, so this does make the map more accurate.

**Review by knelli2 — APPROVED** [review]

**Comment by knelli2** [comment]
Ignoring known CI issues

**Comment by nilsvu** [comment]
@knelli2 thanks for looking at this. Please wait for requested reviews before merging please. @mar-celine if you have any comments still please feel free to leave them here and we can find a way to address them.

**Comment by knelli2** [comment]
Oh sorry @mar-celine I missed that your review was requested

**Pull request merged**
