### PR TITLE
Move Determinant into EagerMath

### PR DESCRIPTION
**Pull request by fmahebert**

### CODE REVIEW

**Comment by fmahebert** [comment]
Rearranges the Tensor math functions and tests as per discussion in #137.

**Comment by nilsdeppe** [comment]
Squash into one commit and :+1:

**Comment by nilsdeppe** [comment]
clang-tidy wants some `&`s

**Comment by nilsdeppe** [comment]
fixup looks good, can't merge until it's either squashed or renamed not to start with `fixup`

**Comment by fmahebert** [comment]
Renamed

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
