### PR TITLE
 Refactor elliptic initializers into actions

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

With PDALs we can now make the initialization a proper phase with an action list. This PR does so for the elliptic code.

- [x] Depends on #1574, so only the last 4 commits are new
- [x] <s>I haven't fixed the tests yet, hence the draft status</s>
- [x] Depends on #1579 so that we don't have to refactor this again

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
This is ready for review now, since all tests are fixed. It still depends on #1574 for convenience, so please ignore the first four commits.

@nilsdeppe would you review this since you do the evolution initializers? @kidder could you find a second reviewer?

A few notes on future plans:
- I expect we can fully share `InitializeDomain` between evolution and elliptic code. We can merge it with @nilsdeppe's upcoming evolution domain initializer.
- `InitializeInterfaces` currently sets up standard interface compute items and also the face normal, which needs the system's magnitude. For magnitudes that depend on system variables I suggest to prepend an initializer that adds the dependencies to the databox. Then, `InitializeSystem` has access to the face tags and can do things like slice variables to faces.
- The evolution initializers will not use `InitializeTemporalId` but do evolution-specific things instead.
- `InitializeMortars` (previously `InitializeDiscontinuousGalerkin`) can probably also be shared between evolution and elliptic systems, by treating (first-order) elliptic systems the same as flux-conservative evolution systems.
- Generally, I suggest to split initializers that we are unsure of into smaller pieces. Then each executable can better decide how to compose the initializer action list in the Metavariables.

**Comment by kidder** [comment]
@nilsleiffischer this isn't compiling...

**Comment by nilsvu** [comment]
@kidder it's compiling fine in clang... gcc is complaining about something which I will of course fix, but I was hoping to get a first round of reviews before worrying about the details.

**Comment by nilsvu** [comment]
This is now rebased on #1579. It moves some initialisers around, generalises them so they can be used by the elliptic code, and adds tests that were omitted in #1579. @nilsdeppe could you review this?

**Comment by nilsvu** [comment]
I'm splitting this into smaller PRs to make it easier to review, starting with #1605, #1606, #1607 and #1608.

**Comment by nilsdeppe** [comment]
@nilsleiffischer is there anything left in this PR that wasn't merged in the 4 others? Can this PR be closed?

**Comment by nilsvu** [comment]
Yes this can be closed 👍

**Pull request closed without merging**
