### PR TITLE
Move YlmSpherepack into namespace

### PR DESCRIPTION
**Pull request by nilsvu**
This fixes segfaults I got when linking in SpEC libraries, probably because of collisions with SpEC's YlmSpherepack class. It's good to establish a namespace for spherical harmonic things anyway.

### Upgrade instructions

`YlmSpherepack` is `ylm::Spherepack` now.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
Is it possible to have SpEC in it's own namespace when using it in SpECTRE to avoid namespace collisions? I don't know much about linking like this or if it would even be possibly, but it seems more robust to not have to worry about changing our code when something is added in SpEC that could possibly conflict.

**Comment by knelli2** [comment]
Is it possible to have SpEC in it's own namespace when using it in SpECTRE to avoid namespace collisions? I don't know much about linking like this or if it would even be possibly, but it seems more robust to not have to worry about changing our code when something is added in SpEC that could possibly conflict.

**Comment by nilsvu** [comment]
Not really I think. You could include the SpEC headers within a namespace, but not sure how robust that is.

**Comment by markscheel** [comment]
Looks good, but is `sh` a long enough name that it is understandable what it means?  Some abbreviations (like `gr`) are obvious, but maybe `spherical_harmonics` or `ylm` might be better.  If everyone else is happy with `sh` then I am ok with it too, but I want to make sure we aren't overlooking a better name.

**Comment by nilsvu** [comment]
I'm not particularly happy about `sh` but I can't think of anything better. I think `spherical_harmonics` is too long for a top-level namespace. Other possible abbreviations are `sph` (can be confused with "smooth particle hydro"), `spherical`, `sphharm`. None a particularly great.

**Comment by knelli2** [comment]
I think `sh` is fine

**Review by knelli2 — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
