### PR TITLE
Support addition and subtraction of doubles with TensorExpressions

### PR DESCRIPTION
**Pull request by macedo22**
## Proposed changes

This PR  implements the addition and subtraction of `double`s with `TensorExpression`s and adds a test for these sums and differences.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

**Comment by macedo22** [comment]
Dependent on https://github.com/sxs-collaboration/spectre/pull/2831 being merged

**Comment by macedo22** [comment]
Hmm looks like some clang-tidy errors in existing code, though I'm not sure why since the flagged syntax appears in other files.

**Comment by nilsdeppe** [comment]
The first error is:
```
Error while processing /__w/spectre/spectre/tests/Unit/DataStructures/Tensor/Expressions/Test_AddSubtract.cpp.
/__w/spectre/spectre/src/DataStructures/Tensor/Expressions/AddSubtract.hpp:14:10: error: 'DataStructures/Tensor/Expressions/NumberAsExpression.hpp' file not found
```
It couldn't find a file (maybe you forgot to commit it?). This means the rest of the errors are not useful since it can't really do an analysis of code that can't compile :)

**Comment by macedo22** [comment]
Oh I didn't connect that not compiling could cause those other errors to appear! I've rebased now that the PR this was dependent on has been merged

**Review by fmahebert — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
