### PR TITLE
Add Wcns5z for ghmhd, add Enable options to LimitLorentz & FixConservatives

### PR DESCRIPTION
**Pull request by nilsdeppe**
### Upgrade instructions

Need to add
```
    Enable: false # Only needed when not using Kastaun for recovery
```
(or `true`) to `FixConservatives` and `LimitLorentzFactor` in input files.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by kidder — APPROVED** [review]

**Review by ermost — APPROVED** [review]

**Comment by ffoucart** [comment]
Seems fine to me; we'll just have to add the lower velocity to the WENO reconstructor's inputs.

**Comment by nilsdeppe** [comment]
I'm trying to find where in develop we have that input. Or is this something you're adding?

**Comment by ffoucart** [comment]
Oh, that's the change you made to all the reconstructors to allow the calculation of the sound speed. It's not in develop; we'll just have to make the change when we merge the sound speed changes.

**Comment by nilsdeppe** [comment]
Ah okay, yea that should be straightforward enough to update when we get there :)

**Pull request merged**
