### PR TITLE
Remove extra braces in initializers

### PR DESCRIPTION
**Pull request by wthrowe**
This lets the code compile with gcc 10, but there are still runtime
problems.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
I can't reproduce the test failure locally.

**Review by fmahebert — DISMISSED** [review]
The clang-tidy failure is already fixed in #2392 #2393 #2402 ... hopefully we can merge one of these soon ... but if not, you can just look up the fix in any of the above.

**Review by nilsvu — DISMISSED** [review]
Looks like there's a random-value test failure that's unrelated to this PR and the known clang-tidy failure that's fixed in other PRs, so I think this PR can be merged as-is.

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — DISMISSED** [review]

**Comment by kidder** [comment]
@wthrowe please rebase

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
