### PR TITLE
Add OmegaDotEccentricityControl.py for SpECTRE

### PR DESCRIPTION
**Pull request by AzerAfram**
## Proposed changes
This script (originally from SpEC) takes in a directory that contains `GhBinaryBlackHoleReductionData.h5` that was outputted from a binary black hole run on SpECTRE (ideally, the binary black hole ran till merger).

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments
Several niche functions have been added to extract the necessary data from the reduction data. If necessary, the script can be altered to utilize only one function for extraction, though this would make the main functions more difficult to read. Additionally, omega, eccentricity, and coordinate separation must be modified (refer to "INPUT" in the file). If necessary, the script can be adjusted to accept these values as parameters instead. If either `/ObservationAhA.dat` or `/ObservationAhB.dat` in `GhBinaryBlackHoleReducitonData.h5` contain less than ~10 entries, refer to `dimensionFullSpins()`.

### CODE REVIEW

**Comment by geoffrey4444** [comment]
@AzerAfram I'm glad you got this to work! But just merging this script would mean any future updates to the spec script would not make it into spectre.

I wonder if you could modify this so that instead of putting in the entire script, you read in the files as you do here, then output an H5 file with the same data in the places the spec script expects? Then you can just use the spec script, rather than using a copy that would have to be maintained every time the spec script gets updated

**Comment by nilsvu** [comment]
Quick note: it's also possible to `import` a script from spec, as is done in `support/Pipelines/EccentricityControl/InitialOrbitalParameters.py`. I can take a closer look at this later.

**Comment by nilsvu** [comment]
Another quick note: there's some discussion on this topic in #5937.

**Comment by AzerAfram** [comment]
@geoffrey4444 Yes, I can and will do that instead. Thank you, @nilsvu.

**Comment by AzerAfram** [comment]
Okay, I've made it so that the script alters `Horizons.h5` where necessary, and also creates an `ID_Params.perl` file with only the required arguments.

**Review by geoffrey4444 — CHANGES_REQUESTED** [review]
Please squash into one commit. I can help you do this you're note sure how.

**Comment by nilsvu** [comment]
Hi @AzerAfram , we've made some progress on the SpEC side of the interface. This PR is about to be merged: https://github.com/sxs-collaboration/spec/pull/2673. It allows you to pass in the trajectories as numpy arrays and returns the updates to the orbital parameters. Could you update this PR to use it, so you don't have to write/edit any H5 files anymore and you don't have to write a Params perl file anymore? Just import and call the `performAllFits` function.

**Comment by AzerAfram** [comment]
Ok, I'll do that.

**Pull request closed without merging**
