### PR TITLE
Split `Normalized` into a simple tag + an inheriting compute tag

### PR DESCRIPTION
**Pull request by prayush**
## Proposed changes

Here we replace the compute tag `Normalized` with a compute tag `NormalizedCompute` that derives off a simple tag `Normalized`..

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
I would prefer we split these into simple tags and compute tags that inherit off them.

**Comment by prayush** [comment]
> I would prefer we split these into simple tags and compute tags that inherit off them.

@wthrowe : Any suggestions for the deriving simple tag's name? `UnitNormed` is the best I got so far :)

**Comment by wthrowe** [comment]
What's wrong with the current name?

**Comment by nilsdeppe** [comment]
I agree with @wthrowe. The interface to compute tags does not include a `type` type alias. In terms of names we've settled on `Blah` for the simple tag and `BlahCompute` for the compute tag. Since the compute tag inherits from the simple tag it can also be retrieved from the DataBox using the simple tag.

**Comment by prayush** [comment]
@wthrowe @nilsdeppe - split `Normalized` into simple and compute tags

**Comment by wthrowe** [comment]
I think we could get this merged faster than #1322 if the changes reverting stuff from there were removed (and then #1322 could use these structures in the first place rather than having to be changed after being merged).

It is hard to judge the fixup on top of the other PR, so I may have missed things here.  At least some of the changes (from #1322 + this) to FaceNormal.hpp should be removed: the `type` alias is not needed and at least some of the new includes should be removed.

**Comment by nilsdeppe** [comment]
Plan is to:
1. Remove upwind as a dependency
2. Make NormalizedCompute and Normalized changes throughout code base as only part of this PR.

Discussion with: @prayush @wthrowe @geoffrey4444 @markscheel @fmahebert @moxcodes @nilsdeppe

**Comment by prayush** [comment]
> I think we could get this merged faster than #1322 if the changes reverting stuff from there were removed (and then #1322 could use these structures in the first place rather than having to be changed after being merged).
> 

> Plan is to:
> 
> 1. Remove upwind as a dependency
> 2. Make NormalizedCompute and Normalized changes throughout code base as only part of this PR.
> 
> Discussion with: @prayush @wthrowe @geoffrey4444 @markscheel @fmahebert @moxcodes @nilsdeppe

I've removed Upwind as a dependency here, and now this PR simply splits `Normalized` to `NormalizedCompute`+`Normalized`.

**Review by nilsdeppe — APPROVED** [review]
LGTM :)

**Review by geoffrey4444 — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]
In the future, try to avoid including formatting changes to files you are not otherwise editing.  (src/Evolution/Systems/GeneralizedHarmonic/Equations.cpp here.)

**Comment by nilsdeppe** [comment]
Travis is not communicating with GitHub. Tests passed: https://travis-ci.org/sxs-collaboration/spectre/builds/533115875?utm_source=github_status&utm_medium=notification

**Pull request merged**
