### PR TITLE
Add normalization to error of InverseJacobianInertialToFluid test

### PR DESCRIPTION
**Pull request by ffoucart**
## Proposed changes

Normalize error used in InverseJacobianInertialToFluid test, to avoid issues when the rng produces unusual metrics and/or large Lorentz factors.

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by ffoucart** [comment]
Meant to fix #5832 
@wthrowe

**Comment by wthrowe** [comment]
Here's another one from testing this on my machine:
```
/home/wthrowe/spectre/tests/Unit/Framework/TestingFramework.hpp:116: FAILED:
  CHECK( a == appx(b) )
with expansion:
  -0.00000000000010898 == Approx( 0.0 )
with messages:
  Seed is: 639487569 from /home/wthrowe/spectre/tests/Unit/Evolution/Particles/
  MonteCarlo/Test_InverseJacobianInertialToFluid.cpp:26
  /home/wthrowe/spectre/tests/Unit/Evolution/Particles/MonteCarlo/
  Test_InverseJacobianInertialToFluid.cpp:96: dot_product_error == norm
  a := (-1.08983e-13,2.53397e-16,-1.75152e-16,-1.96245e-17,0)
  b := (0,0,0,0,0)
```

**Comment by ffoucart** [comment]
In Debug mode? The test passes with that seed for me on wheeler in Release mode...

**Comment by ffoucart** [comment]
```
CHECK( a == appx(b) )
with expansion:
  0.00000000000001462 == Approx( 0.0 )
with messages:
  Seed is: 639487569 from /home/ffoucart/spectre-pr/tests/Unit/Evolution/
  Particles/MonteCarlo/Test_InverseJacobianInertialToFluid.cpp:26
  /home/ffoucart/spectre-pr/tests/Unit/Evolution/Particles/MonteCarlo/
  Test_InverseJacobianInertialToFluid.cpp:94: dot_product_error == norm
  a := (1.46232e-14,-3.70543e-16,-4.54525e-17,1.19478e-16,0)
  b := (0,0,0,0,0)
```

This is what I get, using the same seed (and forcing the error lower to see what error I get... it's an order of magnitude lower)

**Comment by wthrowe** [comment]
From discussion elsewhere, this seems to be hardware-dependent.  By loosening the tolerance from 1e-13 to 5e-13 I was able to run the test 150k times without failure, so I think we can go with that as a fix.

**Comment by ffoucart** [comment]
Pushed change of tolerance and rebased

**Review by wthrowe — APPROVED** [review]

**Pull request merged**
