### PR TITLE
Add serialization of static_vector and fix History serialization

### PR DESCRIPTION
**Pull request by wthrowe**
These are independent things, but the second is three lines and has merge conflicts with the first.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by kidder — APPROVED** [review]

**Comment by nilsvu** [comment]
@wthrowe FYI (just reading the title of the PR): Blaze also has static vectors https://bitbucket.org/blaze-lib/blaze/wiki/Vector%20Types

**Comment by nilsvu** [comment]
Oh and their serialization is already implemented in `src/DataStructures/StaticVector.hpp`

**Comment by wthrowe** [comment]
It's hard to tell because there's not much documentation except explaining the template parameters, but it looks like the Blaze one does something different and just happens to have the same name.

**Comment by nilsvu** [comment]
You're right, they are different. Boost's is dynamically sized with a static capacity, and Blaze's has a fixed size.

**Pull request merged**
