### PR TITLE
Add Kyle to core devs

### PR DESCRIPTION
**Pull request by nilsvu**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — APPROVED** [review]

**Review by knelli2 — APPROVED** [review]
It'd be weird if I didn't approve this, right???

**Comment by nilsvu** [comment]
No, now you have accepted the weight of responsibility :P

**Comment by knelli2** [comment]
🏋🏻‍♂️ 💪🏻

**Comment by nilsdeppe** [comment]
And now you're stuck with it ;) Welcome aboard!

**Pull request merged**
