### PR TITLE
Minor CI cleanup, revive coverage build on CI, update ccache sizes

### PR DESCRIPTION
**Pull request by nilsvu**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

**Comment by kidder** [comment]
did you mean to rename some of the builds?

**Comment by nilsvu** [comment]
Yea removing the `use_xsimd` changed the names anyway, so I made the other names consistent as well.

**Comment by nilsvu** [comment]
Yea removing the `use_xsimd` changed the names anyway, so I made the other names consistent as well.

**Comment by nilsdeppe** [comment]
We in the past intentionally added the info to the build names so it's easier to figure out what might've gone wrong. Can you please keep that? I think not having the PCH is fine, but CMake & Charm variant are important.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsvu** [comment]
I updated ccache sizes as well. Two clang builds didn't have a ccache size configured, so they filled up their default of 5GB, probably reducing cache effectiveness overall.

**Review by kidder — APPROVED** [review]

**Pull request merged**
