### PR TITLE
Add step_function to DataVector

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Add `step_function` to DataVector. This is needed by SpEC and since I wrote it already I figured it is better just to get it into the code than weit.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Review by wthrowe — CHANGES_REQUESTED** [review]
I'm not sure where the most appropriate place for it is, but there needs to be some documentation explaining what `step_function` actually does, since that's a very generic name.

**Comment by nilsdeppe** [comment]
That actually makes me notice that none of the functions are listed anywhere. I'm thinking it might be best to have a list on the DataVector page of all the functions available linking to their documentation. I don't think functions like `sin` really need documentation on what they do, but it should be obvious that it exists. Specifically, I think on DataVector we want something like:

A variety of mathematical operations are supported with DataVectors. In addition to the addition, subtraction, multiplication, division, etc. there are the following element-wise operations:

- tan
- sin
- step_function: if less than zero returns zero, otherwise returns one


Thoughts?

**Comment by wthrowe** [comment]
Yeah, that sounds good.  I agree that any functions that do the same thing as a function of the same name on doubles don't need an explanation.

**Comment by nilsdeppe** [comment]
Alright, I've updated the PR. The documentation for all the math functions actually shows up as "Public Member Functions" in Doxygen (I don't know why, but it does...). I've also added a commit that lists all the functions in the DataVector documentation

**Review by wthrowe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
