### PR TITLE
Add CcsnCollapse as Gh executable

### PR DESCRIPTION
**Pull request by pajkosmi**
## Proposed changes
Allow CcsnCollapse to run for the Gh system.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by pajkosmi** [comment]
Nils, b/c a new template parameter was added to `struct DerivCompute`, I had to add a Meshtag argument to `::Tags::DerivCompute<>` in the *.hpp files in different systems like `EvolveCurvedScalarWave`, `EvolveGhBinaryBlackHole`, etc. Is there a better way I can adjust this, so the CcsnCollapse problem doesn't affect other systems, or is this technical debt small enough?

**Review by nilsdeppe — COMMENTED** [review]
Nope, this is a necessary change because we assume we would only ever have 1 numerical scheme/1 mesh 🙃 We've had a number of sweeping changes like this, and it's just inevitable cleanup/improvements.

The code LGTM, I will ask you to spilt it into a few commits (we can jump on a hangout and go over git surgery if you want, just Slack me). I suggest:
1. Add mesh tag template parameter to deriv compute. This will include all the executable changes where the tag gets added.
2. Add dt_lapse, dt_shift, and dt_spatial_metric to CCSN collapse.
3. Add CcsnCollapse GH executable (this is just the CMake file and the fwd decls)

**Comment by knelli2** [comment]
I think @nilsdeppe's splits for the commit are good. One question for @pajkosmi, for the CCSN physical problem, are you ever going to need to extract waveforms? If you will, then you're changes now are good, but if you won't then I'd remove the `BondiSachs` argument when adding the CCSN executable in the cmake file.

**Comment by nilsdeppe** [comment]
One of the big reasons to use spectre for CCSN is to get GW waveforms :)

**Comment by knelli2** [comment]
Ok! Then definitely leave the `BondiSachs` in

**Comment by pajkosmi** [comment]
@nilsdeppe I have split the commits.

**Review by nilsdeppe — APPROVED** [review]

**Review by knelli2 — APPROVED** [review]

**Pull request merged**
