### PR TITLE
Move functions into anonymous namespaces and similar

### PR DESCRIPTION
**Pull request by wthrowe**
This is based on gcc's `-Wmissing-declarations`, which is for catching global functions that are defined without a declaration in the header (or anywhere else, but declarations are rarely other places).  clang also accepts the flag, but it doesn't seem to work, at least in a simple test.

I've tried to split things up by type of change, and also to separate out anything I could imagine people might object to.

This does not enable the warning in our build system or silence the warning in two places where it is expected, but I can do that if people like the idea.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I haven't looked through the code, but this seems like a useful warning to enable :) It encourages good practice that follows our guidelines so I'm in favor of having the warning!

**Comment by wthrowe** [comment]
Added a commit enabling it.  Easy enough to drop if it causes problems.

Looks like clang implemented the wrong warning when they copied the gcc flag: https://github.com/llvm/llvm-project/issues/16660

**Comment by wthrowe** [comment]
I'll get the python stuff fixed tomorrow.

**Review by nilsdeppe — COMMENTED** [review]
LGTM. I can take a look at the remaining changes for the python files when you've got them. Thanks for cleaning this up! :D

**Comment by wthrowe** [comment]
Rebased on develop, put some stuff in ParallelInfo.cpp in an anonymous namespace (squashed into "Put helper functions in anonymous namespaces"), and added a commit adding headers for the python bindings.

**Review by nilsvu — APPROVED** [review]
❤️

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
