### PR TITLE
Improve YAML formatting of EventsAndTriggers

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Attempt to improve the awkward `- -` syntax in EventsAndTriggers.

### Upgrade instructions

In input files that use EventsAndTriggers, EventsAndDenseTriggers, or PhaseChanges, change the `- -` syntax to something like this:

```yaml
EventsAndTriggers:
  - Trigger:
      Slabs:
        Specified:
          Values: [100]
    Events:
      - Completion
```

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nilsvu** [comment]
Another idea I had is something like this:

```yaml
EventsAndTriggers:
  - When:
      Slabs:
        Specified:
          Values: [100]
    Run:
      - Completion
```

**Comment by wthrowe** [comment]
I like this.  I prefer the "Events" and "Trigger" label version for consistency with the section label.

**Comment by knelli2** [comment]
I like this as well and second @wthrowe's naming conventions.

**Comment by nilsdeppe** [comment]
Same. Much easier to read!

**Comment by nilsvu** [comment]
This is ready for review / merge whenever one of you gets the chance

**Review by wthrowe — APPROVED** [review]
Thanks for also consolidating the duplicate triggers in the example input files.

**Pull request merged**
