### PR TITLE
Catch2 support

### PR DESCRIPTION
**Pull request by wthrowe**
### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### CODE REVIEW

**Comment by nilsdeppe** [comment]
I'm in favor of requiring Catch2, actually. It has a few minor things that are nicer, like not needing extra parens in CHECK statements. That alone will make a fair amount of code a bit cleaner What do others think? I'll put in a PR to get Catch2 into Spack if it isn't already.

**Comment by wthrowe** [comment]
Requiring Catch2 is probably a good idea if it isn't too much of a problem to get it installed everywhere.  As you may realize from the diff here, the behavior of `Approx::custom()` changed and it will be simpler if everyone's setup agrees on what is happening.

**Comment by wthrowe** [comment]
I'm seeing sporadic failures in RNG-using tests.  Probably more scale issues.  I'll investigate when I have time.

**Comment by nilsdeppe** [comment]
I just checked and catch 2.1.0 is in Spack (as well as all versions up to there) so it should be quite easy to get the latest installed everywhere. I can create the module on Wheeler and update the Docker container. The container update will need to wait until this gets merged, so we will want to first get support for Catch2, then see if we can require it.

**Comment by wthrowe** [comment]
Adding a scale in `test_jacobian` in `tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp` seems to have cleared the random failures up.  I've squashed that into the existing changes.

**Review by nilsdeppe — APPROVED** [review]
Okay, awesome! I'm happy to get this merged and then move to requiring Catch2

**Review by kidder — APPROVED** [review]

**Pull request merged**
