### PR TITLE
Simplify clang-format git hook

### LINKED ISSUE #4527: Commit-hook errors with clang 15
```
Traceback (most recent call last):
  File "/home/wthrowe/spectre/.git/hooks/ClangFormat.py", line 65, in <module>
    output = subprocess.check_output([git_executable, clang_format,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/git', 'clang-format', '--diff']' returned non-zero exit status 1.
```

Probably related to https://github.com/llvm/llvm-project/commit/357afd952852db0be3f690f8b647bd4b02f38cad

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

This came up because I looked at the git hooks in #5204 . Changes:

- Use the clang-format binary found by CMake. No need to go through a Python script that finds clang-format binaries.
- Print diffstat to give information on which files need formatting.
- Fix colorization issues (previously I got mangled output in VSCode)

Also fixes #4527.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
> Not writing a patch to the source directory anymore. (If anyone is using this, we can add it back. However, we don't require an exact clang-format version on CI so the exact patch is unimportant. For development it's more useful to know how to run git-clang-format directly than to apply the patch from the commit hook.)

I do use this regularly. I still attempt to clang-format directly, but occasionally I miss a file or two and it's a simple way to not have to think about formatting.

Edit: I don't have strong opinions on this, but if it's easy to keep I'd say keep it.

**Comment by nilsvu** [comment]
Ok I can add it back then

**Comment by wthrowe** [comment]
Do you know if this will fix #4527?

**Comment by nilsvu** [comment]
Yes it does, since I'm running with `clang-format version 15.0.7`. Fixed the script a bit to accommodate the pre-15 behavior.

**Review by nilsdeppe — APPROVED** [review]
@knelli2 @wthrowe could you take a look to see if you're happy with this?

**Review by wthrowe — APPROVED** [review]

**Review by knelli2 — APPROVED** [review]

**Pull request merged**
