### PR TITLE
Don't print traceback for incorrect CLI command

### PR DESCRIPTION
**Pull request by knelli2**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by knelli2** [comment]
@nilsvu I'm not that well-versed in python, so is there a better way to do this?

**Comment by nilsvu** [comment]
Yea set `_rich_traceback_guard = True` before raising the exception. Also, try raising a `click.UsageError` instead of NotImplemented because I think that prints helpful instructions so you you may not have to print the available commands.

**Comment by knelli2** [comment]
Apparently, `click.UsageError` already doesn't print a backtrace so I just went with that

**Review by nilsvu — APPROVED** [review]

**Comment by knelli2** [comment]
@nilsvu Do you think it'd be a good idea to add a new GitHub label called `Python`? I feel like it'd be nice to have to categorize some PRs (like this one)

**Comment by nilsvu** [comment]
I don't see much practical benefit, do you? 🤷‍♂️

**Comment by knelli2** [comment]
Yeah it serves a similar purpose as our other labels. It's just nice to have to sort things. I think it's most similar to the `documentation` label. It's just nice to see when reviewing

**Comment by nilsvu** [comment]
Just FYI, all labels that we currently use have some meaning in code review. `documentation` means "let's not nitpick too much on wording and incomplete bits and such and rather merge this sooner".

**Comment by wthrowe** [comment]
It does?  I always interpreted it as an indicator that you were going to mostly be reviewing prose instead of code, so people who like doing the former would see it.

**Comment by knelli2** [comment]
I had the same thought at @wthrowe. Which is how I envisioned the `Python` label to go. It would say "If you review this PR, it'll be mostly python code"

**Pull request merged**
