### PR TITLE
Add ModalVector

### PR DESCRIPTION
**Pull request by prayush**
## Proposed changes

In response to #378 , this PR adds the `ModalVector` class that has a design similar to `DataVector`, but is intentionally a functional subset of `DataVector`. A `ModalVector` is intended to exclusively hold coefficients of spectral expansion for objects on the computational mesh. Unlike `DataVector`, only **basic** math operations are overloaded for `ModalVector` objects (scalar multiplication and addition) to ensure code safety.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

The current implementation of arithmetic between `ModalVector` and `DataVector` may need improvement.

### CODE REVIEW

**Comment by nilsvu** [comment]
Since this is so close to `DataVector`, is there a way to consolidate the two, perhaps deriving them off a common class?

For a name I think we chose `ModalVector`, or `ModeVector`, or possibly also `SpectralCoefficientVector` (although that‘s just a synonym for modes).

**Comment by wthrowe** [comment]
Does this interact with #696?

**Comment by nilsvu** [comment]
Since `DataVector` and this one don't derive off a Blaze vector class but rather wrap it internally, neither have interactions with the `DenseVector` and `DenseMatrix` by default. That's by design, since we don't want `DataVector` to automatically have a dot product with a `DenseVector` for example, where it's unclear what that would mean.

So instead I was thinking of adding an interface to `DataVector` that looks something like `apply_operator(const DenseMatrix&, const DataVector&, size_t dim, const Mesh&)`. This would replace the current BLAS calls. We could also make this even more explicit by introducing a `MeshOperator` class (or similar) that's basically just a `DenseMatrix` but is templated to strictly apply either to a `DataVector` in a particular dimension (e.g. a differentiation matrix), or a `ModeVector` (e.g. a linear filter matrix), or transforms between them (the Vandermonde matrix). This would ensure that all operations have a well-defined meaning.

**Edit:** I should be more specific. Where `DataVector` right now accepts any Blaze vector expression, e.g for component wise multiplication, also a `DenseVector` would work. Do we want that?

**Comment by nilsdeppe** [comment]
There is currently an ongoing discussion with the Blaze developers to figure out how to "tag" our different vector types: https://bitbucket.org/blaze-lib/blaze/issues/166/allow-tagging-blaze-expressions
Once a solution has been found we will need to change this PR appropriately.

**Comment by prayush** [comment]
@nilsdeppe (or someone with rights to reopen PRs) - could you reopen this PR please? 
[Why? There was an issue that would only show up on one of the travis builds, that I could not reproduce on my machine / wheeler. To track and fix it I had to make multiple dummy commits here. Once fixed, I _recreated_ the branch associated with this PR, and that requires the PR to be reopened]

**Comment by nilsdeppe** [comment]
I believe after a force push over a closed PR a new PR needs to be opened (I don't have a button to reopen either). You can set up Travis to run on your fork too, which I do to debug problems before submitting a PR :) The build times are faster on forks too, than on PRs.

**Comment by prayush** [comment]
@nilsdeppe - yep, on that already so this isnt repeated. In the meanwhile #715 over-rides this (closed) PR.

**Pull request closed without merging**
