### PR TITLE
Remove CCE dependency from Interpolation

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

Addresses the CCE part of #3561.

Moves `SendGhWorldtubeData` to CCE.

### Upgrade instructions

`src/ParallelAlgorithms/Interpolation/Callbacks/SendGhWorldtubeData.hpp` has been moved to `src/Evolution/Systems/Cce/SendGhWorldtubeData.hpp`

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by nikwit** [comment]
maybe it would be more logical to move the callback into `CCE` itself? By forward declaring it, it seems like it can be used without CCE but if the executable does not have CCE as a link target, you will end up with an undefined symbol, or am I not seeing it right?

**Comment by knelli2** [comment]
You're right, but that's true of any forward declaration and we use forward declarations in a lot of places. I guess it's just a preference on whether we want to keep all the interpolation callbacks in the same place or not. I don't see an obvious reason to require them to be in the same place.

Furthermore, up until now, we haven't had any callbacks that truly depended on other libs. But in theory you could write a callback that does depend upon other libs. So in that case, you'd want to store it elsewhere. I think that's enough reason for me to move it to CCE. Does that sound good @nikwit?

**Comment by nikwit** [comment]
I think the reason we use forward declaration is mostly to reduce compilation time so we only include the symbols that we need rather than the entire header. Correct me if I'm wrong but the forward declaration here does not do much in terms of dependencies and I suspect just deleting the link dependency from CMake would also compile and link fine. I agree we should put it into `CCE` to actually get rid of the dependency and so that the symbol can not exist without its definition.

**Comment by knelli2** [comment]
@nikwit ok it has been moved!

**Review by nikwit — APPROVED** [review]
Looks good, but I am not sure if we shouldn't also move it into the CCE namespace? Whaat do you think?

**Comment by knelli2** [comment]
We could, but currently this isn't actually used anywhere except a test so not super important. I think I'll leave it as is for now

**Review by nilsdeppe — APPROVED** [review]

**Pull request merged**
