### PR TITLE
Factor prefix metafunctions

### PR DESCRIPTION
**Pull request by kidder**
## Proposed changes

Factor some more code out of `DataBoxTag.hpp` in an effort to reduce coupling of the code.
Factored out `wrap_tags_in`, `add_tag_prefix`, `remove_tag_prefix`, `remove_all_prefixes`, `variables_tag_with_tags_list`, and `get_variables_tag_list` and put them into `DataStructures/DataBox/PrefixHelpers.hpp`

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by nilsdeppe — COMMENTED** [review]
LGTM. Apparently there are merge conflicts so you'll need to rebase on develop

**Review by fmahebert — COMMENTED** [review]
LGTM as well

**Comment by kidder** [comment]
@nilsdeppe @fmahebert rebased

**Review by nilsdeppe — APPROVED** [review]
image

**Review by fmahebert — APPROVED** [review]

**Pull request merged**
