### PR TITLE
Run algorithm after simple and reduction actions

### PR DESCRIPTION
**Pull request by wthrowe**
The tests for the parallelization framework are complicated, and I do not know what the best way to test this change is.  Suggestions are welcome.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
The unit tests pass, but I'm not confident that this change won't mess up the GMRES algorithm on multiple cores/nodes (we don't test in parallel). In particular, I'm worried that the algorithm continues after the `OrthogonalizeOperand` action instead of waiting for the `NormalizeOperandAndUpdateField` action to complete when run in parallel. I should probably refactor those actions to make use of the `is_ready` functionality instead..

**Comment by wthrowe** [comment]
`perform_algorithm` doesn't do anything if the algorithm is terminated, which I think was what you were doing.

**Comment by nilsvu** [comment]
Ok I'm less worried now 👍

**Review by nilsdeppe — APPROVED** [review]
@nilsleiffischer if you're worried about this breaking your code you already have a bug :) This is perfectly well-defined behavior in our parallelization model

**Comment by fmahebert** [comment]
For my education: what does this change actually mean for the code flow? Can you give an example of when the old behavior would lead to a problem?

**Comment by nilsdeppe** [comment]
One example (I can't say this is what @wthrowe ran into) is that if sent a reduction to all elements of the array and then wanted to perform the algorithm. Currently (before this PR) you would have to call `perform_algorithm()` yourself locally inside the simple/reduction action being executed on the target. Since the actions in the `action_list` for each phase have an `is_ready` function, that should be used to control when the algorithm may continue as anything else is susceptible to race conditions. So the old behavior isn't problematic, it's cumbersome (at least I haven't thought of a problematic case yet). Does that make sense?

**Comment by fmahebert** [comment]
Yes, thanks @nilsdeppe!

**Comment by wthrowe** [comment]
The case where I hit this was for global adaptive time stepping.  Schematically, we have two actions, one to choose the step size and one to set it, and we have to do a global reduction between the two so that all the elements can agree on the new step size.  I would have an element contribute to the reduction and then fail the `is_ready` call for the second action because the reduction hadn't completed, but then when the reduction did complete `is_ready` was not checked again and the algorithm stalled.

Responding to comments that came in while I was typing the above:  Working around this by calling `perform_algorithm()` yourself from a simple/reduction action is tricky, because a synchronous call would return immediately because an action was already executing.

**Comment by kidder** [comment]
ignoring travis timeout

**Pull request merged**
