### PR TITLE
Add hdf5 to Wheeler environment

### PR DESCRIPTION
**Pull request by Sizheng-Ma**

### CODE REVIEW

**Comment by Sizheng-Ma** [comment]
## Proposed changes



### Upgrade instructions






### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

**Comment by kidder** [comment]
Could you please explain in the PR description why you are making this change?  In #2045 we dropped having hdf5 loaded...

**Comment by Sizheng-Ma** [comment]
The conda version is not compiled thread-safe, while the new version is, so this works better for e.g. CCE which does not currently read and write with a strategy that supports non-threadsafe hdf5.

**Comment by nilsdeppe** [comment]
SpECTRE does not require threadsafe HDF5. Any part that does is an error by a developer and should be fixed.

**Comment by moxcodes** [comment]
@nilsdeppe Agreed, and the conversion of CCE read/write to convert observers to that task is on my to-do list, but the conversion and verification of that functionality will be far longer in coming than a 4-line environment change, the (unfortunate) need of threadsafe hdf5 is documented in CCE documentation, and this choice of environment is of practical use to those who want to directly use CCE without altering their environment.

**Comment by nilsdeppe** [comment]
Having 2 HDF5's in the path has led to a lot of problems in the past. There's a reason the HDF5 module isn't loaded: it leads to an inconsistent environment.

**Comment by nilsdeppe** [comment]
To expand: if I remember correctly you get into situations where the build uses the conda headers, but the module at link time, and other weird artifacts. This becomes even more risky if one uses h5py in this environment because that uses the conda HDF5. So unless it can be demonstrated that those things end up all using the module, I don't think we should do load a second HDF5 module, especially an incompatible one.

Edit: my understanding of modules is that it provides a way of isolating different versions of the same library, and so really I think the HDF5 module should be marked as incompatible with python modules not built against it. (building python, other than conda, is a pain, and conda is a huge pain for a variety of other reasons)

**Comment by moxcodes** [comment]
My understanding from those that have used similar environments to this in the past for successful CCE runs is that the link/header clash can be worked around by module ordering -- that ought to be tested more thoroughly, but I believe this order actually works, where loading hdf5 earlier than conda does ensure that the hdf5 is effectively unusable.

The h5py point is a good one, though -- I don't know how to guarantee that the python does not use the conda h5, and I'd have to guess that the only good way of doing so would be to use raw python instead, which would be a far larger environment change for other difficult reasons.

So, if consistency with h5py is a deal-breaker, then I guess we have to just close this and let those running CCE continue to maintain their own environment patches until I manage to fix the reading utilities to not require threadsafe hdf5.

**Pull request closed without merging**
