### PR TITLE
Add CHECK_ALSO variable to iwyu make calls to individual files

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

A proposed assistance for [Issue 1089](https://github.com/sxs-collaboration/spectre/issues/1089). The IWYU check_also flag permits specifying additional headers in the include tree of the checked file.
With this, we can check files as:
```
make iwyu FILE=path/to/including/test.cpp CHECK_ALSO="/full/path/to/spectre/src/Utilities/*.hpp"
```
This will then check the test.cpp and all hpp files in Utilities that are included by it (and I think all Utilities hpp's included by those as well, but I'm less certain of the results on that...)

I was unable to find a way to make the check_also flag work with relative paths.

No fix yet for travis to check the headers, but I could look into that too. I just wanted to post this as the first best thing I thought of in case anyone else had input.

### Types of changes:

- [ ] New feature

### Component:

- [ ] Build system

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by nilsdeppe — APPROVED** [review]
Seems reasonable to me :+1:

**Review by markscheel — APPROVED** [review]
Yay!

**Review by kidder — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]
This is fine for running quick checks, but I don't think it will work for Travis because I can't find a way to pass multiple patterns.  If that's acceptable I'm fine with merging as-is.

**Comment by nilsdeppe** [comment]
I think adding the check to travis should be done as a separate step, since as you say, it'll need to be handled slightly differently :)

**Comment by kidder** [comment]
Yes, let's defer getting this to work with Travis to a separate PR

**Pull request merged**
