### PR TITLE
Small cleanups, mostly to documentation

### PR DESCRIPTION
**Pull request by fmahebert**
Clean some documentation and code.

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by wthrowe** [comment]
IWYU is unhappy, otherwise looks good.

**Comment by fmahebert** [comment]
I squashed a fix of IWYU, and I also added two more cleaning commits.

**Review by kidder — DISMISSED** [review]

**Review by wthrowe — DISMISSED** [review]

**Comment by kidder** [comment]
needs a rebase

**Comment by fmahebert** [comment]
Rebased

**Review by wthrowe — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Pull request merged**
